// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/domain"
)

// NewMockPolicyRepository creates a new instance of MockPolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyRepository {
	mock := &MockPolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyRepository is an autogenerated mock type for the PolicyRepository type
type MockPolicyRepository struct {
	mock.Mock
}

type MockPolicyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyRepository) EXPECT() *MockPolicyRepository_Expecter {
	return &MockPolicyRepository_Expecter{mock: &_m.Mock}
}

// AttachPlatformUserPolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) AttachPlatformUserPolicy(ctx context.Context, userID uint, policyID uint64) error {
	ret := _mock.Called(ctx, userID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for AttachPlatformUserPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint64) error); ok {
		r0 = returnFunc(ctx, userID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_AttachPlatformUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachPlatformUserPolicy'
type MockPolicyRepository_AttachPlatformUserPolicy_Call struct {
	*mock.Call
}

// AttachPlatformUserPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) AttachPlatformUserPolicy(ctx interface{}, userID interface{}, policyID interface{}) *MockPolicyRepository_AttachPlatformUserPolicy_Call {
	return &MockPolicyRepository_AttachPlatformUserPolicy_Call{Call: _e.mock.On("AttachPlatformUserPolicy", ctx, userID, policyID)}
}

func (_c *MockPolicyRepository_AttachPlatformUserPolicy_Call) Run(run func(ctx context.Context, userID uint, policyID uint64)) *MockPolicyRepository_AttachPlatformUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_AttachPlatformUserPolicy_Call) Return(err error) *MockPolicyRepository_AttachPlatformUserPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_AttachPlatformUserPolicy_Call) RunAndReturn(run func(ctx context.Context, userID uint, policyID uint64) error) *MockPolicyRepository_AttachPlatformUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// AttachTenantUserPolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) AttachTenantUserPolicy(ctx context.Context, tenantID string, userID uint, policyID uint64) error {
	ret := _mock.Called(ctx, tenantID, userID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for AttachTenantUserPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, uint64) error); ok {
		r0 = returnFunc(ctx, tenantID, userID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_AttachTenantUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachTenantUserPolicy'
type MockPolicyRepository_AttachTenantUserPolicy_Call struct {
	*mock.Call
}

// AttachTenantUserPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) AttachTenantUserPolicy(ctx interface{}, tenantID interface{}, userID interface{}, policyID interface{}) *MockPolicyRepository_AttachTenantUserPolicy_Call {
	return &MockPolicyRepository_AttachTenantUserPolicy_Call{Call: _e.mock.On("AttachTenantUserPolicy", ctx, tenantID, userID, policyID)}
}

func (_c *MockPolicyRepository_AttachTenantUserPolicy_Call) Run(run func(ctx context.Context, tenantID string, userID uint, policyID uint64)) *MockPolicyRepository_AttachTenantUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_AttachTenantUserPolicy_Call) Return(err error) *MockPolicyRepository_AttachTenantUserPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_AttachTenantUserPolicy_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint, policyID uint64) error) *MockPolicyRepository_AttachTenantUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) CreatePolicy(ctx context.Context, policy domain.Policy, statements []domain.PolicyStatement) (*domain.Policy, []domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, policy, statements)

	if len(ret) == 0 {
		panic("no return value specified for CreatePolicy")
	}

	var r0 *domain.Policy
	var r1 []domain.PolicyStatement
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Policy, []domain.PolicyStatement) (*domain.Policy, []domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, policy, statements)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Policy, []domain.PolicyStatement) *domain.Policy); ok {
		r0 = returnFunc(ctx, policy, statements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Policy, []domain.PolicyStatement) []domain.PolicyStatement); ok {
		r1 = returnFunc(ctx, policy, statements)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.Policy, []domain.PolicyStatement) error); ok {
		r2 = returnFunc(ctx, policy, statements)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPolicyRepository_CreatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePolicy'
type MockPolicyRepository_CreatePolicy_Call struct {
	*mock.Call
}

// CreatePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - policy domain.Policy
//   - statements []domain.PolicyStatement
func (_e *MockPolicyRepository_Expecter) CreatePolicy(ctx interface{}, policy interface{}, statements interface{}) *MockPolicyRepository_CreatePolicy_Call {
	return &MockPolicyRepository_CreatePolicy_Call{Call: _e.mock.On("CreatePolicy", ctx, policy, statements)}
}

func (_c *MockPolicyRepository_CreatePolicy_Call) Run(run func(ctx context.Context, policy domain.Policy, statements []domain.PolicyStatement)) *MockPolicyRepository_CreatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Policy
		if args[1] != nil {
			arg1 = args[1].(domain.Policy)
		}
		var arg2 []domain.PolicyStatement
		if args[2] != nil {
			arg2 = args[2].([]domain.PolicyStatement)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_CreatePolicy_Call) Return(policy1 *domain.Policy, policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_CreatePolicy_Call {
	_c.Call.Return(policy1, policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_CreatePolicy_Call) RunAndReturn(run func(ctx context.Context, policy domain.Policy, statements []domain.PolicyStatement) (*domain.Policy, []domain.PolicyStatement, error)) *MockPolicyRepository_CreatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlatformUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) DeletePlatformUserInlinePolicy(ctx context.Context, userID uint, name string) error {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlatformUserInlinePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_DeletePlatformUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlatformUserInlinePolicy'
type MockPolicyRepository_DeletePlatformUserInlinePolicy_Call struct {
	*mock.Call
}

// DeletePlatformUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
func (_e *MockPolicyRepository_Expecter) DeletePlatformUserInlinePolicy(ctx interface{}, userID interface{}, name interface{}) *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call {
	return &MockPolicyRepository_DeletePlatformUserInlinePolicy_Call{Call: _e.mock.On("DeletePlatformUserInlinePolicy", ctx, userID, name)}
}

func (_c *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call) Run(run func(ctx context.Context, userID uint, name string)) *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call) Return(err error) *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string) error) *MockPolicyRepository_DeletePlatformUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) DeletePolicy(ctx context.Context, policyID uint64) error {
	ret := _mock.Called(ctx, policyID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_DeletePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePolicy'
type MockPolicyRepository_DeletePolicy_Call struct {
	*mock.Call
}

// DeletePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) DeletePolicy(ctx interface{}, policyID interface{}) *MockPolicyRepository_DeletePolicy_Call {
	return &MockPolicyRepository_DeletePolicy_Call{Call: _e.mock.On("DeletePolicy", ctx, policyID)}
}

func (_c *MockPolicyRepository_DeletePolicy_Call) Run(run func(ctx context.Context, policyID uint64)) *MockPolicyRepository_DeletePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_DeletePolicy_Call) Return(err error) *MockPolicyRepository_DeletePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_DeletePolicy_Call) RunAndReturn(run func(ctx context.Context, policyID uint64) error) *MockPolicyRepository_DeletePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTenantUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) DeleteTenantUserInlinePolicy(ctx context.Context, tenantID string, userID uint, name string) error {
	ret := _mock.Called(ctx, tenantID, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTenantUserInlinePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string) error); ok {
		r0 = returnFunc(ctx, tenantID, userID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_DeleteTenantUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTenantUserInlinePolicy'
type MockPolicyRepository_DeleteTenantUserInlinePolicy_Call struct {
	*mock.Call
}

// DeleteTenantUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
//   - name string
func (_e *MockPolicyRepository_Expecter) DeleteTenantUserInlinePolicy(ctx interface{}, tenantID interface{}, userID interface{}, name interface{}) *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call {
	return &MockPolicyRepository_DeleteTenantUserInlinePolicy_Call{Call: _e.mock.On("DeleteTenantUserInlinePolicy", ctx, tenantID, userID, name)}
}

func (_c *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call) Run(run func(ctx context.Context, tenantID string, userID uint, name string)) *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call) Return(err error) *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint, name string) error) *MockPolicyRepository_DeleteTenantUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DetachPlatformUserPolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) DetachPlatformUserPolicy(ctx context.Context, userID uint, policyID uint64) error {
	ret := _mock.Called(ctx, userID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for DetachPlatformUserPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint64) error); ok {
		r0 = returnFunc(ctx, userID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_DetachPlatformUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachPlatformUserPolicy'
type MockPolicyRepository_DetachPlatformUserPolicy_Call struct {
	*mock.Call
}

// DetachPlatformUserPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) DetachPlatformUserPolicy(ctx interface{}, userID interface{}, policyID interface{}) *MockPolicyRepository_DetachPlatformUserPolicy_Call {
	return &MockPolicyRepository_DetachPlatformUserPolicy_Call{Call: _e.mock.On("DetachPlatformUserPolicy", ctx, userID, policyID)}
}

func (_c *MockPolicyRepository_DetachPlatformUserPolicy_Call) Run(run func(ctx context.Context, userID uint, policyID uint64)) *MockPolicyRepository_DetachPlatformUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_DetachPlatformUserPolicy_Call) Return(err error) *MockPolicyRepository_DetachPlatformUserPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_DetachPlatformUserPolicy_Call) RunAndReturn(run func(ctx context.Context, userID uint, policyID uint64) error) *MockPolicyRepository_DetachPlatformUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DetachTenantUserPolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) DetachTenantUserPolicy(ctx context.Context, tenantID string, userID uint, policyID uint64) error {
	ret := _mock.Called(ctx, tenantID, userID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for DetachTenantUserPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, uint64) error); ok {
		r0 = returnFunc(ctx, tenantID, userID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_DetachTenantUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachTenantUserPolicy'
type MockPolicyRepository_DetachTenantUserPolicy_Call struct {
	*mock.Call
}

// DetachTenantUserPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) DetachTenantUserPolicy(ctx interface{}, tenantID interface{}, userID interface{}, policyID interface{}) *MockPolicyRepository_DetachTenantUserPolicy_Call {
	return &MockPolicyRepository_DetachTenantUserPolicy_Call{Call: _e.mock.On("DetachTenantUserPolicy", ctx, tenantID, userID, policyID)}
}

func (_c *MockPolicyRepository_DetachTenantUserPolicy_Call) Run(run func(ctx context.Context, tenantID string, userID uint, policyID uint64)) *MockPolicyRepository_DetachTenantUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_DetachTenantUserPolicy_Call) Return(err error) *MockPolicyRepository_DetachTenantUserPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_DetachTenantUserPolicy_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint, policyID uint64) error) *MockPolicyRepository_DetachTenantUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlatformUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) GetPlatformUserInlinePolicy(ctx context.Context, userID uint, name string) (*domain.UserInlinePolicy, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPlatformUserInlinePolicy")
	}

	var r0 *domain.UserInlinePolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*domain.UserInlinePolicy, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *domain.UserInlinePolicy); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserInlinePolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_GetPlatformUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlatformUserInlinePolicy'
type MockPolicyRepository_GetPlatformUserInlinePolicy_Call struct {
	*mock.Call
}

// GetPlatformUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
func (_e *MockPolicyRepository_Expecter) GetPlatformUserInlinePolicy(ctx interface{}, userID interface{}, name interface{}) *MockPolicyRepository_GetPlatformUserInlinePolicy_Call {
	return &MockPolicyRepository_GetPlatformUserInlinePolicy_Call{Call: _e.mock.On("GetPlatformUserInlinePolicy", ctx, userID, name)}
}

func (_c *MockPolicyRepository_GetPlatformUserInlinePolicy_Call) Run(run func(ctx context.Context, userID uint, name string)) *MockPolicyRepository_GetPlatformUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_GetPlatformUserInlinePolicy_Call) Return(userInlinePolicy *domain.UserInlinePolicy, err error) *MockPolicyRepository_GetPlatformUserInlinePolicy_Call {
	_c.Call.Return(userInlinePolicy, err)
	return _c
}

func (_c *MockPolicyRepository_GetPlatformUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string) (*domain.UserInlinePolicy, error)) *MockPolicyRepository_GetPlatformUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicyByName provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) GetPolicyByName(ctx context.Context, name string) (*domain.Policy, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyByName")
	}

	var r0 *domain.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Policy, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Policy); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_GetPolicyByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicyByName'
type MockPolicyRepository_GetPolicyByName_Call struct {
	*mock.Call
}

// GetPolicyByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPolicyRepository_Expecter) GetPolicyByName(ctx interface{}, name interface{}) *MockPolicyRepository_GetPolicyByName_Call {
	return &MockPolicyRepository_GetPolicyByName_Call{Call: _e.mock.On("GetPolicyByName", ctx, name)}
}

func (_c *MockPolicyRepository_GetPolicyByName_Call) Run(run func(ctx context.Context, name string)) *MockPolicyRepository_GetPolicyByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_GetPolicyByName_Call) Return(policy *domain.Policy, err error) *MockPolicyRepository_GetPolicyByName_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *MockPolicyRepository_GetPolicyByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Policy, error)) *MockPolicyRepository_GetPolicyByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicyStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) GetPolicyStatements(ctx context.Context, policyID uint64) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, policyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, policyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, policyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_GetPolicyStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicyStatements'
type MockPolicyRepository_GetPolicyStatements_Call struct {
	*mock.Call
}

// GetPolicyStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) GetPolicyStatements(ctx interface{}, policyID interface{}) *MockPolicyRepository_GetPolicyStatements_Call {
	return &MockPolicyRepository_GetPolicyStatements_Call{Call: _e.mock.On("GetPolicyStatements", ctx, policyID)}
}

func (_c *MockPolicyRepository_GetPolicyStatements_Call) Run(run func(ctx context.Context, policyID uint64)) *MockPolicyRepository_GetPolicyStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_GetPolicyStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_GetPolicyStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_GetPolicyStatements_Call) RunAndReturn(run func(ctx context.Context, policyID uint64) ([]domain.PolicyStatement, error)) *MockPolicyRepository_GetPolicyStatements_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) GetTenantUserInlinePolicy(ctx context.Context, tenantID string, userID uint, name string) (*domain.UserInlinePolicy, error) {
	ret := _mock.Called(ctx, tenantID, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantUserInlinePolicy")
	}

	var r0 *domain.UserInlinePolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string) (*domain.UserInlinePolicy, error)); ok {
		return returnFunc(ctx, tenantID, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string) *domain.UserInlinePolicy); ok {
		r0 = returnFunc(ctx, tenantID, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserInlinePolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint, string) error); ok {
		r1 = returnFunc(ctx, tenantID, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_GetTenantUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantUserInlinePolicy'
type MockPolicyRepository_GetTenantUserInlinePolicy_Call struct {
	*mock.Call
}

// GetTenantUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
//   - name string
func (_e *MockPolicyRepository_Expecter) GetTenantUserInlinePolicy(ctx interface{}, tenantID interface{}, userID interface{}, name interface{}) *MockPolicyRepository_GetTenantUserInlinePolicy_Call {
	return &MockPolicyRepository_GetTenantUserInlinePolicy_Call{Call: _e.mock.On("GetTenantUserInlinePolicy", ctx, tenantID, userID, name)}
}

func (_c *MockPolicyRepository_GetTenantUserInlinePolicy_Call) Run(run func(ctx context.Context, tenantID string, userID uint, name string)) *MockPolicyRepository_GetTenantUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_GetTenantUserInlinePolicy_Call) Return(userInlinePolicy *domain.UserInlinePolicy, err error) *MockPolicyRepository_GetTenantUserInlinePolicy_Call {
	_c.Call.Return(userInlinePolicy, err)
	return _c
}

func (_c *MockPolicyRepository_GetTenantUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint, name string) (*domain.UserInlinePolicy, error)) *MockPolicyRepository_GetTenantUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlatformGroupStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPlatformGroupStatements(ctx context.Context, userID uint) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPlatformGroupStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPlatformGroupStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlatformGroupStatements'
type MockPolicyRepository_ListPlatformGroupStatements_Call struct {
	*mock.Call
}

// ListPlatformGroupStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListPlatformGroupStatements(ctx interface{}, userID interface{}) *MockPolicyRepository_ListPlatformGroupStatements_Call {
	return &MockPolicyRepository_ListPlatformGroupStatements_Call{Call: _e.mock.On("ListPlatformGroupStatements", ctx, userID)}
}

func (_c *MockPolicyRepository_ListPlatformGroupStatements_Call) Run(run func(ctx context.Context, userID uint)) *MockPolicyRepository_ListPlatformGroupStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPlatformGroupStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_ListPlatformGroupStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_ListPlatformGroupStatements_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]domain.PolicyStatement, error)) *MockPolicyRepository_ListPlatformGroupStatements_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlatformUserInlinePolicies provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPlatformUserInlinePolicies(ctx context.Context, userID uint) ([]domain.UserInlinePolicy, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPlatformUserInlinePolicies")
	}

	var r0 []domain.UserInlinePolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.UserInlinePolicy, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.UserInlinePolicy); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserInlinePolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPlatformUserInlinePolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlatformUserInlinePolicies'
type MockPolicyRepository_ListPlatformUserInlinePolicies_Call struct {
	*mock.Call
}

// ListPlatformUserInlinePolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListPlatformUserInlinePolicies(ctx interface{}, userID interface{}) *MockPolicyRepository_ListPlatformUserInlinePolicies_Call {
	return &MockPolicyRepository_ListPlatformUserInlinePolicies_Call{Call: _e.mock.On("ListPlatformUserInlinePolicies", ctx, userID)}
}

func (_c *MockPolicyRepository_ListPlatformUserInlinePolicies_Call) Run(run func(ctx context.Context, userID uint)) *MockPolicyRepository_ListPlatformUserInlinePolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserInlinePolicies_Call) Return(userInlinePolicys []domain.UserInlinePolicy, err error) *MockPolicyRepository_ListPlatformUserInlinePolicies_Call {
	_c.Call.Return(userInlinePolicys, err)
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserInlinePolicies_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]domain.UserInlinePolicy, error)) *MockPolicyRepository_ListPlatformUserInlinePolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlatformUserPolicies provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPlatformUserPolicies(ctx context.Context, userID uint) ([]domain.Policy, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPlatformUserPolicies")
	}

	var r0 []domain.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Policy, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.Policy); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPlatformUserPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlatformUserPolicies'
type MockPolicyRepository_ListPlatformUserPolicies_Call struct {
	*mock.Call
}

// ListPlatformUserPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListPlatformUserPolicies(ctx interface{}, userID interface{}) *MockPolicyRepository_ListPlatformUserPolicies_Call {
	return &MockPolicyRepository_ListPlatformUserPolicies_Call{Call: _e.mock.On("ListPlatformUserPolicies", ctx, userID)}
}

func (_c *MockPolicyRepository_ListPlatformUserPolicies_Call) Run(run func(ctx context.Context, userID uint)) *MockPolicyRepository_ListPlatformUserPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserPolicies_Call) Return(policys []domain.Policy, err error) *MockPolicyRepository_ListPlatformUserPolicies_Call {
	_c.Call.Return(policys, err)
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserPolicies_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]domain.Policy, error)) *MockPolicyRepository_ListPlatformUserPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlatformUserStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPlatformUserStatements(ctx context.Context, userID uint) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPlatformUserStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPlatformUserStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlatformUserStatements'
type MockPolicyRepository_ListPlatformUserStatements_Call struct {
	*mock.Call
}

// ListPlatformUserStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListPlatformUserStatements(ctx interface{}, userID interface{}) *MockPolicyRepository_ListPlatformUserStatements_Call {
	return &MockPolicyRepository_ListPlatformUserStatements_Call{Call: _e.mock.On("ListPlatformUserStatements", ctx, userID)}
}

func (_c *MockPolicyRepository_ListPlatformUserStatements_Call) Run(run func(ctx context.Context, userID uint)) *MockPolicyRepository_ListPlatformUserStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_ListPlatformUserStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_ListPlatformUserStatements_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]domain.PolicyStatement, error)) *MockPolicyRepository_ListPlatformUserStatements_Call {
	_c.Call.Return(run)
	return _c
}

// ListPolicies provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPolicies(ctx context.Context, scope string) ([]domain.Policy, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListPolicies")
	}

	var r0 []domain.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Policy, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Policy); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPolicies'
type MockPolicyRepository_ListPolicies_Call struct {
	*mock.Call
}

// ListPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *MockPolicyRepository_Expecter) ListPolicies(ctx interface{}, scope interface{}) *MockPolicyRepository_ListPolicies_Call {
	return &MockPolicyRepository_ListPolicies_Call{Call: _e.mock.On("ListPolicies", ctx, scope)}
}

func (_c *MockPolicyRepository_ListPolicies_Call) Run(run func(ctx context.Context, scope string)) *MockPolicyRepository_ListPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPolicies_Call) Return(policys []domain.Policy, err error) *MockPolicyRepository_ListPolicies_Call {
	_c.Call.Return(policys, err)
	return _c
}

func (_c *MockPolicyRepository_ListPolicies_Call) RunAndReturn(run func(ctx context.Context, scope string) ([]domain.Policy, error)) *MockPolicyRepository_ListPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListPolicyAttachments provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListPolicyAttachments(ctx context.Context, policyID uint64) ([]domain.PolicyAttachment, error) {
	ret := _mock.Called(ctx, policyID)

	if len(ret) == 0 {
		panic("no return value specified for ListPolicyAttachments")
	}

	var r0 []domain.PolicyAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.PolicyAttachment, error)); ok {
		return returnFunc(ctx, policyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []domain.PolicyAttachment); ok {
		r0 = returnFunc(ctx, policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, policyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListPolicyAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPolicyAttachments'
type MockPolicyRepository_ListPolicyAttachments_Call struct {
	*mock.Call
}

// ListPolicyAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - policyID uint64
func (_e *MockPolicyRepository_Expecter) ListPolicyAttachments(ctx interface{}, policyID interface{}) *MockPolicyRepository_ListPolicyAttachments_Call {
	return &MockPolicyRepository_ListPolicyAttachments_Call{Call: _e.mock.On("ListPolicyAttachments", ctx, policyID)}
}

func (_c *MockPolicyRepository_ListPolicyAttachments_Call) Run(run func(ctx context.Context, policyID uint64)) *MockPolicyRepository_ListPolicyAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListPolicyAttachments_Call) Return(policyAttachments []domain.PolicyAttachment, err error) *MockPolicyRepository_ListPolicyAttachments_Call {
	_c.Call.Return(policyAttachments, err)
	return _c
}

func (_c *MockPolicyRepository_ListPolicyAttachments_Call) RunAndReturn(run func(ctx context.Context, policyID uint64) ([]domain.PolicyAttachment, error)) *MockPolicyRepository_ListPolicyAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoleStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListRoleStatements(ctx context.Context, roleID uint64) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for ListRoleStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListRoleStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoleStatements'
type MockPolicyRepository_ListRoleStatements_Call struct {
	*mock.Call
}

// ListRoleStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockPolicyRepository_Expecter) ListRoleStatements(ctx interface{}, roleID interface{}) *MockPolicyRepository_ListRoleStatements_Call {
	return &MockPolicyRepository_ListRoleStatements_Call{Call: _e.mock.On("ListRoleStatements", ctx, roleID)}
}

func (_c *MockPolicyRepository_ListRoleStatements_Call) Run(run func(ctx context.Context, roleID uint64)) *MockPolicyRepository_ListRoleStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListRoleStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_ListRoleStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_ListRoleStatements_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) ([]domain.PolicyStatement, error)) *MockPolicyRepository_ListRoleStatements_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantGroupStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListTenantGroupStatements(ctx context.Context, tenantID string, userID uint) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantGroupStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListTenantGroupStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantGroupStatements'
type MockPolicyRepository_ListTenantGroupStatements_Call struct {
	*mock.Call
}

// ListTenantGroupStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListTenantGroupStatements(ctx interface{}, tenantID interface{}, userID interface{}) *MockPolicyRepository_ListTenantGroupStatements_Call {
	return &MockPolicyRepository_ListTenantGroupStatements_Call{Call: _e.mock.On("ListTenantGroupStatements", ctx, tenantID, userID)}
}

func (_c *MockPolicyRepository_ListTenantGroupStatements_Call) Run(run func(ctx context.Context, tenantID string, userID uint)) *MockPolicyRepository_ListTenantGroupStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListTenantGroupStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_ListTenantGroupStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_ListTenantGroupStatements_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint) ([]domain.PolicyStatement, error)) *MockPolicyRepository_ListTenantGroupStatements_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantUserInlinePolicies provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListTenantUserInlinePolicies(ctx context.Context, tenantID string, userID uint) ([]domain.UserInlinePolicy, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantUserInlinePolicies")
	}

	var r0 []domain.UserInlinePolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) ([]domain.UserInlinePolicy, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) []domain.UserInlinePolicy); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserInlinePolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListTenantUserInlinePolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantUserInlinePolicies'
type MockPolicyRepository_ListTenantUserInlinePolicies_Call struct {
	*mock.Call
}

// ListTenantUserInlinePolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListTenantUserInlinePolicies(ctx interface{}, tenantID interface{}, userID interface{}) *MockPolicyRepository_ListTenantUserInlinePolicies_Call {
	return &MockPolicyRepository_ListTenantUserInlinePolicies_Call{Call: _e.mock.On("ListTenantUserInlinePolicies", ctx, tenantID, userID)}
}

func (_c *MockPolicyRepository_ListTenantUserInlinePolicies_Call) Run(run func(ctx context.Context, tenantID string, userID uint)) *MockPolicyRepository_ListTenantUserInlinePolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserInlinePolicies_Call) Return(userInlinePolicys []domain.UserInlinePolicy, err error) *MockPolicyRepository_ListTenantUserInlinePolicies_Call {
	_c.Call.Return(userInlinePolicys, err)
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserInlinePolicies_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint) ([]domain.UserInlinePolicy, error)) *MockPolicyRepository_ListTenantUserInlinePolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantUserPolicies provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListTenantUserPolicies(ctx context.Context, tenantID string, userID uint) ([]domain.Policy, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantUserPolicies")
	}

	var r0 []domain.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) ([]domain.Policy, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) []domain.Policy); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListTenantUserPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantUserPolicies'
type MockPolicyRepository_ListTenantUserPolicies_Call struct {
	*mock.Call
}

// ListTenantUserPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListTenantUserPolicies(ctx interface{}, tenantID interface{}, userID interface{}) *MockPolicyRepository_ListTenantUserPolicies_Call {
	return &MockPolicyRepository_ListTenantUserPolicies_Call{Call: _e.mock.On("ListTenantUserPolicies", ctx, tenantID, userID)}
}

func (_c *MockPolicyRepository_ListTenantUserPolicies_Call) Run(run func(ctx context.Context, tenantID string, userID uint)) *MockPolicyRepository_ListTenantUserPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserPolicies_Call) Return(policys []domain.Policy, err error) *MockPolicyRepository_ListTenantUserPolicies_Call {
	_c.Call.Return(policys, err)
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserPolicies_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint) ([]domain.Policy, error)) *MockPolicyRepository_ListTenantUserPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantUserStatements provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) ListTenantUserStatements(ctx context.Context, tenantID string, userID uint) ([]domain.PolicyStatement, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantUserStatements")
	}

	var r0 []domain.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) ([]domain.PolicyStatement, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) []domain.PolicyStatement); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRepository_ListTenantUserStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantUserStatements'
type MockPolicyRepository_ListTenantUserStatements_Call struct {
	*mock.Call
}

// ListTenantUserStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
func (_e *MockPolicyRepository_Expecter) ListTenantUserStatements(ctx interface{}, tenantID interface{}, userID interface{}) *MockPolicyRepository_ListTenantUserStatements_Call {
	return &MockPolicyRepository_ListTenantUserStatements_Call{Call: _e.mock.On("ListTenantUserStatements", ctx, tenantID, userID)}
}

func (_c *MockPolicyRepository_ListTenantUserStatements_Call) Run(run func(ctx context.Context, tenantID string, userID uint)) *MockPolicyRepository_ListTenantUserStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserStatements_Call) Return(policyStatements []domain.PolicyStatement, err error) *MockPolicyRepository_ListTenantUserStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockPolicyRepository_ListTenantUserStatements_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint) ([]domain.PolicyStatement, error)) *MockPolicyRepository_ListTenantUserStatements_Call {
	_c.Call.Return(run)
	return _c
}

// PutPlatformUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) PutPlatformUserInlinePolicy(ctx context.Context, input domain.PutPlatformUserInlinePolicyInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutPlatformUserInlinePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PutPlatformUserInlinePolicyInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_PutPlatformUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPlatformUserInlinePolicy'
type MockPolicyRepository_PutPlatformUserInlinePolicy_Call struct {
	*mock.Call
}

// PutPlatformUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.PutPlatformUserInlinePolicyInput
func (_e *MockPolicyRepository_Expecter) PutPlatformUserInlinePolicy(ctx interface{}, input interface{}) *MockPolicyRepository_PutPlatformUserInlinePolicy_Call {
	return &MockPolicyRepository_PutPlatformUserInlinePolicy_Call{Call: _e.mock.On("PutPlatformUserInlinePolicy", ctx, input)}
}

func (_c *MockPolicyRepository_PutPlatformUserInlinePolicy_Call) Run(run func(ctx context.Context, input domain.PutPlatformUserInlinePolicyInput)) *MockPolicyRepository_PutPlatformUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PutPlatformUserInlinePolicyInput
		if args[1] != nil {
			arg1 = args[1].(domain.PutPlatformUserInlinePolicyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_PutPlatformUserInlinePolicy_Call) Return(err error) *MockPolicyRepository_PutPlatformUserInlinePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_PutPlatformUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, input domain.PutPlatformUserInlinePolicyInput) error) *MockPolicyRepository_PutPlatformUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// PutTenantUserInlinePolicy provides a mock function for the type MockPolicyRepository
func (_mock *MockPolicyRepository) PutTenantUserInlinePolicy(ctx context.Context, input domain.PutTenantUserInlinePolicyInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutTenantUserInlinePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PutTenantUserInlinePolicyInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyRepository_PutTenantUserInlinePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTenantUserInlinePolicy'
type MockPolicyRepository_PutTenantUserInlinePolicy_Call struct {
	*mock.Call
}

// PutTenantUserInlinePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.PutTenantUserInlinePolicyInput
func (_e *MockPolicyRepository_Expecter) PutTenantUserInlinePolicy(ctx interface{}, input interface{}) *MockPolicyRepository_PutTenantUserInlinePolicy_Call {
	return &MockPolicyRepository_PutTenantUserInlinePolicy_Call{Call: _e.mock.On("PutTenantUserInlinePolicy", ctx, input)}
}

func (_c *MockPolicyRepository_PutTenantUserInlinePolicy_Call) Run(run func(ctx context.Context, input domain.PutTenantUserInlinePolicyInput)) *MockPolicyRepository_PutTenantUserInlinePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PutTenantUserInlinePolicyInput
		if args[1] != nil {
			arg1 = args[1].(domain.PutTenantUserInlinePolicyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRepository_PutTenantUserInlinePolicy_Call) Return(err error) *MockPolicyRepository_PutTenantUserInlinePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyRepository_PutTenantUserInlinePolicy_Call) RunAndReturn(run func(ctx context.Context, input domain.PutTenantUserInlinePolicyInput) error) *MockPolicyRepository_PutTenantUserInlinePolicy_Call {
	_c.Call.Return(run)
	return _c
}
