// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/pkg/messaging"
)

// NewMockInboxStore creates a new instance of MockInboxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInboxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInboxStore {
	mock := &MockInboxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInboxStore is an autogenerated mock type for the InboxStore type
type MockInboxStore struct {
	mock.Mock
}

type MockInboxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInboxStore) EXPECT() *MockInboxStore_Expecter {
	return &MockInboxStore_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockInboxStore
func (_mock *MockInboxStore) Begin(ctx context.Context, consumerName string, messageID string, now time.Time) (messaging.InboxDecision, error) {
	ret := _mock.Called(ctx, consumerName, messageID, now)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 messaging.InboxDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (messaging.InboxDecision, error)); ok {
		return returnFunc(ctx, consumerName, messageID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) messaging.InboxDecision); ok {
		r0 = returnFunc(ctx, consumerName, messageID, now)
	} else {
		r0 = ret.Get(0).(messaging.InboxDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, consumerName, messageID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInboxStore_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockInboxStore_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
//   - consumerName string
//   - messageID string
//   - now time.Time
func (_e *MockInboxStore_Expecter) Begin(ctx interface{}, consumerName interface{}, messageID interface{}, now interface{}) *MockInboxStore_Begin_Call {
	return &MockInboxStore_Begin_Call{Call: _e.mock.On("Begin", ctx, consumerName, messageID, now)}
}

func (_c *MockInboxStore_Begin_Call) Run(run func(ctx context.Context, consumerName string, messageID string, now time.Time)) *MockInboxStore_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInboxStore_Begin_Call) Return(inboxDecision messaging.InboxDecision, err error) *MockInboxStore_Begin_Call {
	_c.Call.Return(inboxDecision, err)
	return _c
}

func (_c *MockInboxStore_Begin_Call) RunAndReturn(run func(ctx context.Context, consumerName string, messageID string, now time.Time) (messaging.InboxDecision, error)) *MockInboxStore_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockInboxStore
func (_mock *MockInboxStore) Complete(ctx context.Context, consumerName string, messageID string, processedAt time.Time) error {
	ret := _mock.Called(ctx, consumerName, messageID, processedAt)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, consumerName, messageID, processedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInboxStore_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockInboxStore_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - consumerName string
//   - messageID string
//   - processedAt time.Time
func (_e *MockInboxStore_Expecter) Complete(ctx interface{}, consumerName interface{}, messageID interface{}, processedAt interface{}) *MockInboxStore_Complete_Call {
	return &MockInboxStore_Complete_Call{Call: _e.mock.On("Complete", ctx, consumerName, messageID, processedAt)}
}

func (_c *MockInboxStore_Complete_Call) Run(run func(ctx context.Context, consumerName string, messageID string, processedAt time.Time)) *MockInboxStore_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInboxStore_Complete_Call) Return(err error) *MockInboxStore_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInboxStore_Complete_Call) RunAndReturn(run func(ctx context.Context, consumerName string, messageID string, processedAt time.Time) error) *MockInboxStore_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type MockInboxStore
func (_mock *MockInboxStore) Fail(ctx context.Context, consumerName string, messageID string, errText string, failedAt time.Time) error {
	ret := _mock.Called(ctx, consumerName, messageID, errText, failedAt)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, consumerName, messageID, errText, failedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInboxStore_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockInboxStore_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - consumerName string
//   - messageID string
//   - errText string
//   - failedAt time.Time
func (_e *MockInboxStore_Expecter) Fail(ctx interface{}, consumerName interface{}, messageID interface{}, errText interface{}, failedAt interface{}) *MockInboxStore_Fail_Call {
	return &MockInboxStore_Fail_Call{Call: _e.mock.On("Fail", ctx, consumerName, messageID, errText, failedAt)}
}

func (_c *MockInboxStore_Fail_Call) Run(run func(ctx context.Context, consumerName string, messageID string, errText string, failedAt time.Time)) *MockInboxStore_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInboxStore_Fail_Call) Return(err error) *MockInboxStore_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInboxStore_Fail_Call) RunAndReturn(run func(ctx context.Context, consumerName string, messageID string, errText string, failedAt time.Time) error) *MockInboxStore_Fail_Call {
	_c.Call.Return(run)
	return _c
}
