// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/pkg/messaging"
)

// NewMockErrorClassifier creates a new instance of MockErrorClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorClassifier {
	mock := &MockErrorClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorClassifier is an autogenerated mock type for the ErrorClassifier type
type MockErrorClassifier struct {
	mock.Mock
}

type MockErrorClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorClassifier) EXPECT() *MockErrorClassifier_Expecter {
	return &MockErrorClassifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function for the type MockErrorClassifier
func (_mock *MockErrorClassifier) Classify(ctx context.Context, msg messaging.Envelope, err error) messaging.FailureClassification {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 messaging.FailureClassification
	if returnFunc, ok := ret.Get(0).(func(context.Context, messaging.Envelope, error) messaging.FailureClassification); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Get(0).(messaging.FailureClassification)
	}
	return r0
}

// MockErrorClassifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockErrorClassifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - msg messaging.Envelope
//   - err error
func (_e *MockErrorClassifier_Expecter) Classify(ctx interface{}, msg interface{}, err interface{}) *MockErrorClassifier_Classify_Call {
	return &MockErrorClassifier_Classify_Call{Call: _e.mock.On("Classify", ctx, msg, err)}
}

func (_c *MockErrorClassifier_Classify_Call) Run(run func(ctx context.Context, msg messaging.Envelope, err error)) *MockErrorClassifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 messaging.Envelope
		if args[1] != nil {
			arg1 = args[1].(messaging.Envelope)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockErrorClassifier_Classify_Call) Return(failureClassification messaging.FailureClassification) *MockErrorClassifier_Classify_Call {
	_c.Call.Return(failureClassification)
	return _c
}

func (_c *MockErrorClassifier_Classify_Call) RunAndReturn(run func(ctx context.Context, msg messaging.Envelope, err error) messaging.FailureClassification) *MockErrorClassifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}
