ALTER TABLE routed_orders
	ADD COLUMN IF NOT EXISTS shipment_status TEXT NOT NULL DEFAULT 'awaiting_label',
	ADD COLUMN IF NOT EXISTS shipment_carrier TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS shipment_tracking_number TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS shipment_tracking_url TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS shipment_notes TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ NULL;
