ALTER TABLE routed_orders
	ADD COLUMN IF NOT EXISTS base_cost_snapshot TEXT NOT NULL DEFAULT '$0.00',
	ADD COLUMN IF NOT EXISTS fulfillment_cost TEXT NOT NULL DEFAULT '$0.00',
	ADD COLUMN IF NOT EXISTS shipping_cost TEXT NOT NULL DEFAULT '$0.00',
	ADD COLUMN IF NOT EXISTS realized_margin TEXT NOT NULL DEFAULT '$0.00',
	ADD COLUMN IF NOT EXISTS settlement_status TEXT NOT NULL DEFAULT 'pending',
	ADD COLUMN IF NOT EXISTS settlement_notes TEXT NOT NULL DEFAULT '';
