ALTER TABLE routed_orders
	ADD COLUMN IF NOT EXISTS issue_cost TEXT NOT NULL DEFAULT '$0.00',
	ADD COLUMN IF NOT EXISTS issue_resolution TEXT NOT NULL DEFAULT 'monitor',
	ADD COLUMN IF NOT EXISTS issue_notes TEXT NOT NULL DEFAULT '';
