all: false
pkgname: mocks
template: testify
filename: "mock_{{.InterfaceName}}.go"
formatter: goimports
force-file-write: true

packages:
  github.com/tuannm99/podzone/pkg/pdlog:
    config:
      dir: pkg/pdlog/mocks
    interfaces:
      Logger:

  github.com/tuannm99/podzone/pkg/toolkit/kvstores:
    config:
      dir: pkg/toolkit/kvstores/mocks
    interfaces:
      KVStore:

  github.com/tuannm99/podzone/pkg/pdtenantdb:
    config:
      dir: pkg/pdtenantdb/mocks
    interfaces:
      Manager:
      PlacementResolver:
      ClusterRegistry:

  github.com/tuannm99/podzone/internal/auth/domain/inputport:
    config:
      dir: internal/auth/domain/inputport/mocks
    interfaces:
      AuthUsecase:
      TokenUsecase:
      UserUsecase:

  github.com/tuannm99/podzone/internal/auth/domain/outputport:
    config:
      dir: internal/auth/domain/outputport/mocks
    interfaces:
      GoogleOauthExternal:
      OauthStateRepository:
      UserRepository:
