FROM node:20-alpine AS builder

ARG SERVICE_NAME
WORKDIR /app

COPY ./services/${SERVICE_NAME}/package*.json ./
RUN npm install

COPY ./services/${SERVICE_NAME}/ .

ARG VITE_ADMIN_API_URL
ENV VITE_ADMIN_API_URL=${VITE_ADMIN_API_URL}

RUN npm run build

# ─────────────────────────────

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist .
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

