apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: podzone

build:
  artifacts:
    - image: podzone-auth
      context: .
      docker:
        dockerfile: services/auth/Dockerfile
  local:
    push: false
    useDockerCLI: true

manifests:
  rawYaml:
    - deployments/kubernetes/services/*.yml

deploy:
  kubectl: {}
  kubeContext: default
