logger:
  provider: zap # zap | slog
  level: debug
  env: dev
  app_name: podzone_onboarding

redis:
  auth:
    uri: '${REDIS_ONBOARDING_DSN}'

mongo:
  onboarding:
    uri: '${MONGO_ONBOARDING_DSN}'
    database: onboarding
    ping_timeout: 3s
    connect_timeout: 5s

onboarding:
  store_provisioning:
    enabled: true
    auto_approve: true
    interval: 5s
    runtime: local_docker
    cluster_name: pg-default
    mode: schema
    db_name: postgres
    schema_prefix: t_
    docker_network: docker_default
    kubernetes_namespace: default
    terraform_workspace: default

grpc:
  port: 50051
