// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/backoffice/domain/store"
)

// NewMockStoreUsecase creates a new instance of MockStoreUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreUsecase {
	mock := &MockStoreUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreUsecase is an autogenerated mock type for the StoreUsecase type
type MockStoreUsecase struct {
	mock.Mock
}

type MockStoreUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreUsecase) EXPECT() *MockStoreUsecase_Expecter {
	return &MockStoreUsecase_Expecter{mock: &_m.Mock}
}

// CreateStore provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) CreateStore(ctx context.Context, name string, description string) (*store.Store, error) {
	ret := _mock.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*store.Store, error)); ok {
		return returnFunc(ctx, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *store.Store); ok {
		r0 = returnFunc(ctx, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_CreateStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStore'
type MockStoreUsecase_CreateStore_Call struct {
	*mock.Call
}

// CreateStore is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
func (_e *MockStoreUsecase_Expecter) CreateStore(ctx interface{}, name interface{}, description interface{}) *MockStoreUsecase_CreateStore_Call {
	return &MockStoreUsecase_CreateStore_Call{Call: _e.mock.On("CreateStore", ctx, name, description)}
}

func (_c *MockStoreUsecase_CreateStore_Call) Run(run func(ctx context.Context, name string, description string)) *MockStoreUsecase_CreateStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_CreateStore_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_CreateStore_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_CreateStore_Call) RunAndReturn(run func(ctx context.Context, name string, description string) (*store.Store, error)) *MockStoreUsecase_CreateStore_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStoreFromCommand provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) CreateStoreFromCommand(ctx context.Context, cmd store.CreateStoreCmd) (*store.Store, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateStoreFromCommand")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateStoreCmd) (*store.Store, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateStoreCmd) *store.Store); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateStoreCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_CreateStoreFromCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStoreFromCommand'
type MockStoreUsecase_CreateStoreFromCommand_Call struct {
	*mock.Call
}

// CreateStoreFromCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd store.CreateStoreCmd
func (_e *MockStoreUsecase_Expecter) CreateStoreFromCommand(ctx interface{}, cmd interface{}) *MockStoreUsecase_CreateStoreFromCommand_Call {
	return &MockStoreUsecase_CreateStoreFromCommand_Call{Call: _e.mock.On("CreateStoreFromCommand", ctx, cmd)}
}

func (_c *MockStoreUsecase_CreateStoreFromCommand_Call) Run(run func(ctx context.Context, cmd store.CreateStoreCmd)) *MockStoreUsecase_CreateStoreFromCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateStoreCmd
		if args[1] != nil {
			arg1 = args[1].(store.CreateStoreCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_CreateStoreFromCommand_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_CreateStoreFromCommand_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_CreateStoreFromCommand_Call) RunAndReturn(run func(ctx context.Context, cmd store.CreateStoreCmd) (*store.Store, error)) *MockStoreUsecase_CreateStoreFromCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllStores provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) GetAllStores(ctx context.Context) ([]store.Store, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStores")
	}

	var r0 []store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]store.Store, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []store.Store); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_GetAllStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStores'
type MockStoreUsecase_GetAllStores_Call struct {
	*mock.Call
}

// GetAllStores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStoreUsecase_Expecter) GetAllStores(ctx interface{}) *MockStoreUsecase_GetAllStores_Call {
	return &MockStoreUsecase_GetAllStores_Call{Call: _e.mock.On("GetAllStores", ctx)}
}

func (_c *MockStoreUsecase_GetAllStores_Call) Run(run func(ctx context.Context)) *MockStoreUsecase_GetAllStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_GetAllStores_Call) Return(stores []store.Store, err error) *MockStoreUsecase_GetAllStores_Call {
	_c.Call.Return(stores, err)
	return _c
}

func (_c *MockStoreUsecase_GetAllStores_Call) RunAndReturn(run func(ctx context.Context) ([]store.Store, error)) *MockStoreUsecase_GetAllStores_Call {
	_c.Call.Return(run)
	return _c
}

// GetStore provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) GetStore(ctx context.Context, query store.GetStoreQuery) (*store.Store, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStore")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.GetStoreQuery) (*store.Store, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.GetStoreQuery) *store.Store); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.GetStoreQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_GetStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStore'
type MockStoreUsecase_GetStore_Call struct {
	*mock.Call
}

// GetStore is a helper method to define mock.On call
//   - ctx context.Context
//   - query store.GetStoreQuery
func (_e *MockStoreUsecase_Expecter) GetStore(ctx interface{}, query interface{}) *MockStoreUsecase_GetStore_Call {
	return &MockStoreUsecase_GetStore_Call{Call: _e.mock.On("GetStore", ctx, query)}
}

func (_c *MockStoreUsecase_GetStore_Call) Run(run func(ctx context.Context, query store.GetStoreQuery)) *MockStoreUsecase_GetStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.GetStoreQuery
		if args[1] != nil {
			arg1 = args[1].(store.GetStoreQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_GetStore_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_GetStore_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_GetStore_Call) RunAndReturn(run func(ctx context.Context, query store.GetStoreQuery) (*store.Store, error)) *MockStoreUsecase_GetStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetStoreByID provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) GetStoreByID(ctx context.Context, id string) (*store.Store, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStoreByID")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*store.Store, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *store.Store); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_GetStoreByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStoreByID'
type MockStoreUsecase_GetStoreByID_Call struct {
	*mock.Call
}

// GetStoreByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStoreUsecase_Expecter) GetStoreByID(ctx interface{}, id interface{}) *MockStoreUsecase_GetStoreByID_Call {
	return &MockStoreUsecase_GetStoreByID_Call{Call: _e.mock.On("GetStoreByID", ctx, id)}
}

func (_c *MockStoreUsecase_GetStoreByID_Call) Run(run func(ctx context.Context, id string)) *MockStoreUsecase_GetStoreByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_GetStoreByID_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_GetStoreByID_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_GetStoreByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*store.Store, error)) *MockStoreUsecase_GetStoreByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListStores provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) ListStores(ctx context.Context, query store.ListStoresQuery) ([]store.Store, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListStores")
	}

	var r0 []store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.ListStoresQuery) ([]store.Store, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.ListStoresQuery) []store.Store); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.ListStoresQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_ListStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStores'
type MockStoreUsecase_ListStores_Call struct {
	*mock.Call
}

// ListStores is a helper method to define mock.On call
//   - ctx context.Context
//   - query store.ListStoresQuery
func (_e *MockStoreUsecase_Expecter) ListStores(ctx interface{}, query interface{}) *MockStoreUsecase_ListStores_Call {
	return &MockStoreUsecase_ListStores_Call{Call: _e.mock.On("ListStores", ctx, query)}
}

func (_c *MockStoreUsecase_ListStores_Call) Run(run func(ctx context.Context, query store.ListStoresQuery)) *MockStoreUsecase_ListStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.ListStoresQuery
		if args[1] != nil {
			arg1 = args[1].(store.ListStoresQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_ListStores_Call) Return(stores []store.Store, err error) *MockStoreUsecase_ListStores_Call {
	_c.Call.Return(stores, err)
	return _c
}

func (_c *MockStoreUsecase_ListStores_Call) RunAndReturn(run func(ctx context.Context, query store.ListStoresQuery) ([]store.Store, error)) *MockStoreUsecase_ListStores_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStoreStatus provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) UpdateStoreStatus(ctx context.Context, id string, active bool) (*store.Store, error) {
	ret := _mock.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStoreStatus")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*store.Store, error)); ok {
		return returnFunc(ctx, id, active)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *store.Store); ok {
		r0 = returnFunc(ctx, id, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, id, active)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_UpdateStoreStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStoreStatus'
type MockStoreUsecase_UpdateStoreStatus_Call struct {
	*mock.Call
}

// UpdateStoreStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - active bool
func (_e *MockStoreUsecase_Expecter) UpdateStoreStatus(ctx interface{}, id interface{}, active interface{}) *MockStoreUsecase_UpdateStoreStatus_Call {
	return &MockStoreUsecase_UpdateStoreStatus_Call{Call: _e.mock.On("UpdateStoreStatus", ctx, id, active)}
}

func (_c *MockStoreUsecase_UpdateStoreStatus_Call) Run(run func(ctx context.Context, id string, active bool)) *MockStoreUsecase_UpdateStoreStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_UpdateStoreStatus_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_UpdateStoreStatus_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_UpdateStoreStatus_Call) RunAndReturn(run func(ctx context.Context, id string, active bool) (*store.Store, error)) *MockStoreUsecase_UpdateStoreStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStoreStatusFromCommand provides a mock function for the type MockStoreUsecase
func (_mock *MockStoreUsecase) UpdateStoreStatusFromCommand(ctx context.Context, cmd store.UpdateStoreStatusCmd) (*store.Store, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStoreStatusFromCommand")
	}

	var r0 *store.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.UpdateStoreStatusCmd) (*store.Store, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.UpdateStoreStatusCmd) *store.Store); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.UpdateStoreStatusCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreUsecase_UpdateStoreStatusFromCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStoreStatusFromCommand'
type MockStoreUsecase_UpdateStoreStatusFromCommand_Call struct {
	*mock.Call
}

// UpdateStoreStatusFromCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd store.UpdateStoreStatusCmd
func (_e *MockStoreUsecase_Expecter) UpdateStoreStatusFromCommand(ctx interface{}, cmd interface{}) *MockStoreUsecase_UpdateStoreStatusFromCommand_Call {
	return &MockStoreUsecase_UpdateStoreStatusFromCommand_Call{Call: _e.mock.On("UpdateStoreStatusFromCommand", ctx, cmd)}
}

func (_c *MockStoreUsecase_UpdateStoreStatusFromCommand_Call) Run(run func(ctx context.Context, cmd store.UpdateStoreStatusCmd)) *MockStoreUsecase_UpdateStoreStatusFromCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.UpdateStoreStatusCmd
		if args[1] != nil {
			arg1 = args[1].(store.UpdateStoreStatusCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreUsecase_UpdateStoreStatusFromCommand_Call) Return(store1 *store.Store, err error) *MockStoreUsecase_UpdateStoreStatusFromCommand_Call {
	_c.Call.Return(store1, err)
	return _c
}

func (_c *MockStoreUsecase_UpdateStoreStatusFromCommand_Call) RunAndReturn(run func(ctx context.Context, cmd store.UpdateStoreStatusCmd) (*store.Store, error)) *MockStoreUsecase_UpdateStoreStatusFromCommand_Call {
	_c.Call.Return(run)
	return _c
}
