apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
spec:
  addresses:
    # k3s private ip range installed on my machine is 10.47.188.x
    # - 10.47.188.100-10.47.188.200
    # if using kind (run inside docker container)
    # - 172.18.0.100-172.18.0.200
    # - 46.250.230.153/32
    - 161.97.108.30-161.97.108.200
  autoAssign: true

