// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/entity"
)

// NewMockOrganizationRepository creates a new instance of MockOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type MockOrganizationRepository struct {
	mock.Mock
}

type MockOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepository) EXPECT() *MockOrganizationRepository_Expecter {
	return &MockOrganizationRepository_Expecter{mock: &_m.Mock}
}

// AttachServiceControlPolicy provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) AttachServiceControlPolicy(ctx context.Context, orgID string, policyID uint64) error {
	ret := _mock.Called(ctx, orgID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for AttachServiceControlPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = returnFunc(ctx, orgID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_AttachServiceControlPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachServiceControlPolicy'
type MockOrganizationRepository_AttachServiceControlPolicy_Call struct {
	*mock.Call
}

// AttachServiceControlPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - policyID uint64
func (_e *MockOrganizationRepository_Expecter) AttachServiceControlPolicy(ctx interface{}, orgID interface{}, policyID interface{}) *MockOrganizationRepository_AttachServiceControlPolicy_Call {
	return &MockOrganizationRepository_AttachServiceControlPolicy_Call{Call: _e.mock.On("AttachServiceControlPolicy", ctx, orgID, policyID)}
}

func (_c *MockOrganizationRepository_AttachServiceControlPolicy_Call) Run(run func(ctx context.Context, orgID string, policyID uint64)) *MockOrganizationRepository_AttachServiceControlPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_AttachServiceControlPolicy_Call) Return(err error) *MockOrganizationRepository_AttachServiceControlPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_AttachServiceControlPolicy_Call) RunAndReturn(run func(ctx context.Context, orgID string, policyID uint64) error) *MockOrganizationRepository_AttachServiceControlPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Create(ctx context.Context, org entity.Organization) (*entity.Organization, error) {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Organization) (*entity.Organization, error)); ok {
		return returnFunc(ctx, org)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Organization) *entity.Organization); ok {
		r0 = returnFunc(ctx, org)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Organization) error); ok {
		r1 = returnFunc(ctx, org)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrganizationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org entity.Organization
func (_e *MockOrganizationRepository_Expecter) Create(ctx interface{}, org interface{}) *MockOrganizationRepository_Create_Call {
	return &MockOrganizationRepository_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *MockOrganizationRepository_Create_Call) Run(run func(ctx context.Context, org entity.Organization)) *MockOrganizationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Organization
		if args[1] != nil {
			arg1 = args[1].(entity.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) Return(organization *entity.Organization, err error) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, org entity.Organization) (*entity.Organization, error)) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DetachServiceControlPolicy provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) DetachServiceControlPolicy(ctx context.Context, orgID string, policyID uint64) error {
	ret := _mock.Called(ctx, orgID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for DetachServiceControlPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = returnFunc(ctx, orgID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_DetachServiceControlPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachServiceControlPolicy'
type MockOrganizationRepository_DetachServiceControlPolicy_Call struct {
	*mock.Call
}

// DetachServiceControlPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - policyID uint64
func (_e *MockOrganizationRepository_Expecter) DetachServiceControlPolicy(ctx interface{}, orgID interface{}, policyID interface{}) *MockOrganizationRepository_DetachServiceControlPolicy_Call {
	return &MockOrganizationRepository_DetachServiceControlPolicy_Call{Call: _e.mock.On("DetachServiceControlPolicy", ctx, orgID, policyID)}
}

func (_c *MockOrganizationRepository_DetachServiceControlPolicy_Call) Run(run func(ctx context.Context, orgID string, policyID uint64)) *MockOrganizationRepository_DetachServiceControlPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_DetachServiceControlPolicy_Call) Return(err error) *MockOrganizationRepository_DetachServiceControlPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_DetachServiceControlPolicy_Call) RunAndReturn(run func(ctx context.Context, orgID string, policyID uint64) error) *MockOrganizationRepository_DetachServiceControlPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) GetByID(ctx context.Context, orgID string) (*entity.Organization, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Organization, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Organization); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrganizationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationRepository_Expecter) GetByID(ctx interface{}, orgID interface{}) *MockOrganizationRepository_GetByID_Call {
	return &MockOrganizationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orgID)}
}

func (_c *MockOrganizationRepository_GetByID_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_GetByID_Call) Return(organization *entity.Organization, err error) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, orgID string) (*entity.Organization, error)) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) List(ctx context.Context) ([]entity.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrganizationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizationRepository_Expecter) List(ctx interface{}) *MockOrganizationRepository_List_Call {
	return &MockOrganizationRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockOrganizationRepository_List_Call) Run(run func(ctx context.Context)) *MockOrganizationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_List_Call) Return(organizations []entity.Organization, err error) *MockOrganizationRepository_List_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockOrganizationRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Organization, error)) *MockOrganizationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceControlPolicies provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) ListServiceControlPolicies(ctx context.Context, orgID string) ([]entity.Policy, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceControlPolicies")
	}

	var r0 []entity.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.Policy, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.Policy); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_ListServiceControlPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceControlPolicies'
type MockOrganizationRepository_ListServiceControlPolicies_Call struct {
	*mock.Call
}

// ListServiceControlPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationRepository_Expecter) ListServiceControlPolicies(ctx interface{}, orgID interface{}) *MockOrganizationRepository_ListServiceControlPolicies_Call {
	return &MockOrganizationRepository_ListServiceControlPolicies_Call{Call: _e.mock.On("ListServiceControlPolicies", ctx, orgID)}
}

func (_c *MockOrganizationRepository_ListServiceControlPolicies_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationRepository_ListServiceControlPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_ListServiceControlPolicies_Call) Return(policys []entity.Policy, err error) *MockOrganizationRepository_ListServiceControlPolicies_Call {
	_c.Call.Return(policys, err)
	return _c
}

func (_c *MockOrganizationRepository_ListServiceControlPolicies_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]entity.Policy, error)) *MockOrganizationRepository_ListServiceControlPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceControlPolicyStatements provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) ListServiceControlPolicyStatements(ctx context.Context, orgID string) ([]entity.PolicyStatement, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceControlPolicyStatements")
	}

	var r0 []entity.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entity.PolicyStatement, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entity.PolicyStatement); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_ListServiceControlPolicyStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceControlPolicyStatements'
type MockOrganizationRepository_ListServiceControlPolicyStatements_Call struct {
	*mock.Call
}

// ListServiceControlPolicyStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationRepository_Expecter) ListServiceControlPolicyStatements(ctx interface{}, orgID interface{}) *MockOrganizationRepository_ListServiceControlPolicyStatements_Call {
	return &MockOrganizationRepository_ListServiceControlPolicyStatements_Call{Call: _e.mock.On("ListServiceControlPolicyStatements", ctx, orgID)}
}

func (_c *MockOrganizationRepository_ListServiceControlPolicyStatements_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationRepository_ListServiceControlPolicyStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_ListServiceControlPolicyStatements_Call) Return(policyStatements []entity.PolicyStatement, err error) *MockOrganizationRepository_ListServiceControlPolicyStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockOrganizationRepository_ListServiceControlPolicyStatements_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]entity.PolicyStatement, error)) *MockOrganizationRepository_ListServiceControlPolicyStatements_Call {
	_c.Call.Return(run)
	return _c
}
