// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/entity"
)

// NewMockPlatformMembershipRepository creates a new instance of MockPlatformMembershipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatformMembershipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatformMembershipRepository {
	mock := &MockPlatformMembershipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatformMembershipRepository is an autogenerated mock type for the PlatformMembershipRepository type
type MockPlatformMembershipRepository struct {
	mock.Mock
}

type MockPlatformMembershipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatformMembershipRepository) EXPECT() *MockPlatformMembershipRepository_Expecter {
	return &MockPlatformMembershipRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockPlatformMembershipRepository
func (_mock *MockPlatformMembershipRepository) Delete(ctx context.Context, userID uint, roleID uint64) error {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint64) error); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatformMembershipRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPlatformMembershipRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - roleID uint64
func (_e *MockPlatformMembershipRepository_Expecter) Delete(ctx interface{}, userID interface{}, roleID interface{}) *MockPlatformMembershipRepository_Delete_Call {
	return &MockPlatformMembershipRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, roleID)}
}

func (_c *MockPlatformMembershipRepository_Delete_Call) Run(run func(ctx context.Context, userID uint, roleID uint64)) *MockPlatformMembershipRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlatformMembershipRepository_Delete_Call) Return(err error) *MockPlatformMembershipRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatformMembershipRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uint, roleID uint64) error) *MockPlatformMembershipRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockPlatformMembershipRepository
func (_mock *MockPlatformMembershipRepository) ListByUser(ctx context.Context, userID uint) ([]entity.PlatformMembership, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.PlatformMembership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]entity.PlatformMembership, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []entity.PlatformMembership); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlatformMembership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformMembershipRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockPlatformMembershipRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPlatformMembershipRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockPlatformMembershipRepository_ListByUser_Call {
	return &MockPlatformMembershipRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockPlatformMembershipRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint)) *MockPlatformMembershipRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformMembershipRepository_ListByUser_Call) Return(platformMemberships []entity.PlatformMembership, err error) *MockPlatformMembershipRepository_ListByUser_Call {
	_c.Call.Return(platformMemberships, err)
	return _c
}

func (_c *MockPlatformMembershipRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]entity.PlatformMembership, error)) *MockPlatformMembershipRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoleIDsByUser provides a mock function for the type MockPlatformMembershipRepository
func (_mock *MockPlatformMembershipRepository) ListRoleIDsByUser(ctx context.Context, userID uint) ([]uint64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRoleIDsByUser")
	}

	var r0 []uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]uint64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []uint64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatformMembershipRepository_ListRoleIDsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoleIDsByUser'
type MockPlatformMembershipRepository_ListRoleIDsByUser_Call struct {
	*mock.Call
}

// ListRoleIDsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockPlatformMembershipRepository_Expecter) ListRoleIDsByUser(ctx interface{}, userID interface{}) *MockPlatformMembershipRepository_ListRoleIDsByUser_Call {
	return &MockPlatformMembershipRepository_ListRoleIDsByUser_Call{Call: _e.mock.On("ListRoleIDsByUser", ctx, userID)}
}

func (_c *MockPlatformMembershipRepository_ListRoleIDsByUser_Call) Run(run func(ctx context.Context, userID uint)) *MockPlatformMembershipRepository_ListRoleIDsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatformMembershipRepository_ListRoleIDsByUser_Call) Return(uint64s []uint64, err error) *MockPlatformMembershipRepository_ListRoleIDsByUser_Call {
	_c.Call.Return(uint64s, err)
	return _c
}

func (_c *MockPlatformMembershipRepository_ListRoleIDsByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]uint64, error)) *MockPlatformMembershipRepository_ListRoleIDsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockPlatformMembershipRepository
func (_mock *MockPlatformMembershipRepository) Upsert(ctx context.Context, userID uint, roleID uint64, status string) error {
	ret := _mock.Called(ctx, userID, roleID, status)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint64, string) error); ok {
		r0 = returnFunc(ctx, userID, roleID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatformMembershipRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockPlatformMembershipRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - roleID uint64
//   - status string
func (_e *MockPlatformMembershipRepository_Expecter) Upsert(ctx interface{}, userID interface{}, roleID interface{}, status interface{}) *MockPlatformMembershipRepository_Upsert_Call {
	return &MockPlatformMembershipRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, userID, roleID, status)}
}

func (_c *MockPlatformMembershipRepository_Upsert_Call) Run(run func(ctx context.Context, userID uint, roleID uint64, status string)) *MockPlatformMembershipRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlatformMembershipRepository_Upsert_Call) Return(err error) *MockPlatformMembershipRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatformMembershipRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, userID uint, roleID uint64, status string) error) *MockPlatformMembershipRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
