// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/entity"
)

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) Create(ctx context.Context, log entity.AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log entity.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx interface{}, log interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, log entity.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.AuditLog
		if args[1] != nil {
			arg1 = args[1].(entity.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(err error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, log entity.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
