// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/onboarding/infrasmanager/entity"
)

// NewMockConnectionStore creates a new instance of MockConnectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionStore {
	mock := &MockConnectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionStore is an autogenerated mock type for the ConnectionStore type
type MockConnectionStore struct {
	mock.Mock
}

type MockConnectionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionStore) EXPECT() *MockConnectionStore_Expecter {
	return &MockConnectionStore_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) AppendEvent(ev entity.ConnectionEvent) error {
	ret := _mock.Called(ev)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(entity.ConnectionEvent) error); ok {
		r0 = returnFunc(ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type MockConnectionStore_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ev entity.ConnectionEvent
func (_e *MockConnectionStore_Expecter) AppendEvent(ev interface{}) *MockConnectionStore_AppendEvent_Call {
	return &MockConnectionStore_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ev)}
}

func (_c *MockConnectionStore_AppendEvent_Call) Run(run func(ev entity.ConnectionEvent)) *MockConnectionStore_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.ConnectionEvent
		if args[0] != nil {
			arg0 = args[0].(entity.ConnectionEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_AppendEvent_Call) Return(err error) *MockConnectionStore_AppendEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_AppendEvent_Call) RunAndReturn(run func(ev entity.ConnectionEvent) error) *MockConnectionStore_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueOutbox provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) EnqueueOutbox(msg entity.OutboxMessage) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(entity.OutboxMessage) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_EnqueueOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueOutbox'
type MockConnectionStore_EnqueueOutbox_Call struct {
	*mock.Call
}

// EnqueueOutbox is a helper method to define mock.On call
//   - msg entity.OutboxMessage
func (_e *MockConnectionStore_Expecter) EnqueueOutbox(msg interface{}) *MockConnectionStore_EnqueueOutbox_Call {
	return &MockConnectionStore_EnqueueOutbox_Call{Call: _e.mock.On("EnqueueOutbox", msg)}
}

func (_c *MockConnectionStore_EnqueueOutbox_Call) Run(run func(msg entity.OutboxMessage)) *MockConnectionStore_EnqueueOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.OutboxMessage
		if args[0] != nil {
			arg0 = args[0].(entity.OutboxMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_EnqueueOutbox_Call) Return(err error) *MockConnectionStore_EnqueueOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_EnqueueOutbox_Call) RunAndReturn(run func(msg entity.OutboxMessage) error) *MockConnectionStore_EnqueueOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureIndexes provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) EnsureIndexes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIndexes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_EnsureIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIndexes'
type MockConnectionStore_EnsureIndexes_Call struct {
	*mock.Call
}

// EnsureIndexes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectionStore_Expecter) EnsureIndexes(ctx interface{}) *MockConnectionStore_EnsureIndexes_Call {
	return &MockConnectionStore_EnsureIndexes_Call{Call: _e.mock.On("EnsureIndexes", ctx)}
}

func (_c *MockConnectionStore_EnsureIndexes_Call) Run(run func(ctx context.Context)) *MockConnectionStore_EnsureIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_EnsureIndexes_Call) Return(err error) *MockConnectionStore_EnsureIndexes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_EnsureIndexes_Call) RunAndReturn(run func(ctx context.Context) error) *MockConnectionStore_EnsureIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// FindDueOutbox provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) FindDueOutbox(limit int) ([]entity.OutboxMessage, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for FindDueOutbox")
	}

	var r0 []entity.OutboxMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]entity.OutboxMessage, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []entity.OutboxMessage); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OutboxMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_FindDueOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDueOutbox'
type MockConnectionStore_FindDueOutbox_Call struct {
	*mock.Call
}

// FindDueOutbox is a helper method to define mock.On call
//   - limit int
func (_e *MockConnectionStore_Expecter) FindDueOutbox(limit interface{}) *MockConnectionStore_FindDueOutbox_Call {
	return &MockConnectionStore_FindDueOutbox_Call{Call: _e.mock.On("FindDueOutbox", limit)}
}

func (_c *MockConnectionStore_FindDueOutbox_Call) Run(run func(limit int)) *MockConnectionStore_FindDueOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_FindDueOutbox_Call) Return(outboxMessages []entity.OutboxMessage, err error) *MockConnectionStore_FindDueOutbox_Call {
	_c.Call.Return(outboxMessages, err)
	return _c
}

func (_c *MockConnectionStore_FindDueOutbox_Call) RunAndReturn(run func(limit int) ([]entity.OutboxMessage, error)) *MockConnectionStore_FindDueOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) Get(tenantID string, infraType entity.InfraType, name string) (*entity.ConnectionInfo, error) {
	ret := _mock.Called(tenantID, infraType, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.ConnectionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, string) (*entity.ConnectionInfo, error)); ok {
		return returnFunc(tenantID, infraType, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, string) *entity.ConnectionInfo); ok {
		r0 = returnFunc(tenantID, infraType, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ConnectionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.InfraType, string) error); ok {
		r1 = returnFunc(tenantID, infraType, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConnectionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tenantID string
//   - infraType entity.InfraType
//   - name string
func (_e *MockConnectionStore_Expecter) Get(tenantID interface{}, infraType interface{}, name interface{}) *MockConnectionStore_Get_Call {
	return &MockConnectionStore_Get_Call{Call: _e.mock.On("Get", tenantID, infraType, name)}
}

func (_c *MockConnectionStore_Get_Call) Run(run func(tenantID string, infraType entity.InfraType, name string)) *MockConnectionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.InfraType
		if args[1] != nil {
			arg1 = args[1].(entity.InfraType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionStore_Get_Call) Return(connectionInfo *entity.ConnectionInfo, err error) *MockConnectionStore_Get_Call {
	_c.Call.Return(connectionInfo, err)
	return _c
}

func (_c *MockConnectionStore_Get_Call) RunAndReturn(run func(tenantID string, infraType entity.InfraType, name string) (*entity.ConnectionInfo, error)) *MockConnectionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListConnections provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) ListConnections(tenantID string, infraType entity.InfraType, includeDeleted bool, limit int, offset int) ([]entity.ConnectionInfo, error) {
	ret := _mock.Called(tenantID, infraType, includeDeleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListConnections")
	}

	var r0 []entity.ConnectionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, bool, int, int) ([]entity.ConnectionInfo, error)); ok {
		return returnFunc(tenantID, infraType, includeDeleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, bool, int, int) []entity.ConnectionInfo); ok {
		r0 = returnFunc(tenantID, infraType, includeDeleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ConnectionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.InfraType, bool, int, int) error); ok {
		r1 = returnFunc(tenantID, infraType, includeDeleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_ListConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnections'
type MockConnectionStore_ListConnections_Call struct {
	*mock.Call
}

// ListConnections is a helper method to define mock.On call
//   - tenantID string
//   - infraType entity.InfraType
//   - includeDeleted bool
//   - limit int
//   - offset int
func (_e *MockConnectionStore_Expecter) ListConnections(tenantID interface{}, infraType interface{}, includeDeleted interface{}, limit interface{}, offset interface{}) *MockConnectionStore_ListConnections_Call {
	return &MockConnectionStore_ListConnections_Call{Call: _e.mock.On("ListConnections", tenantID, infraType, includeDeleted, limit, offset)}
}

func (_c *MockConnectionStore_ListConnections_Call) Run(run func(tenantID string, infraType entity.InfraType, includeDeleted bool, limit int, offset int)) *MockConnectionStore_ListConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.InfraType
		if args[1] != nil {
			arg1 = args[1].(entity.InfraType)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockConnectionStore_ListConnections_Call) Return(connectionInfos []entity.ConnectionInfo, err error) *MockConnectionStore_ListConnections_Call {
	_c.Call.Return(connectionInfos, err)
	return _c
}

func (_c *MockConnectionStore_ListConnections_Call) RunAndReturn(run func(tenantID string, infraType entity.InfraType, includeDeleted bool, limit int, offset int) ([]entity.ConnectionInfo, error)) *MockConnectionStore_ListConnections_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) ListEvents(tenantID string, infraType entity.InfraType, name string, correlationID string, limit int, offset int) ([]entity.ConnectionEvent, error) {
	ret := _mock.Called(tenantID, infraType, name, correlationID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []entity.ConnectionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, string, string, int, int) ([]entity.ConnectionEvent, error)); ok {
		return returnFunc(tenantID, infraType, name, correlationID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, string, string, int, int) []entity.ConnectionEvent); ok {
		r0 = returnFunc(tenantID, infraType, name, correlationID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ConnectionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.InfraType, string, string, int, int) error); ok {
		r1 = returnFunc(tenantID, infraType, name, correlationID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockConnectionStore_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - tenantID string
//   - infraType entity.InfraType
//   - name string
//   - correlationID string
//   - limit int
//   - offset int
func (_e *MockConnectionStore_Expecter) ListEvents(tenantID interface{}, infraType interface{}, name interface{}, correlationID interface{}, limit interface{}, offset interface{}) *MockConnectionStore_ListEvents_Call {
	return &MockConnectionStore_ListEvents_Call{Call: _e.mock.On("ListEvents", tenantID, infraType, name, correlationID, limit, offset)}
}

func (_c *MockConnectionStore_ListEvents_Call) Run(run func(tenantID string, infraType entity.InfraType, name string, correlationID string, limit int, offset int)) *MockConnectionStore_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.InfraType
		if args[1] != nil {
			arg1 = args[1].(entity.InfraType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockConnectionStore_ListEvents_Call) Return(connectionEvents []entity.ConnectionEvent, err error) *MockConnectionStore_ListEvents_Call {
	_c.Call.Return(connectionEvents, err)
	return _c
}

func (_c *MockConnectionStore_ListEvents_Call) RunAndReturn(run func(tenantID string, infraType entity.InfraType, name string, correlationID string, limit int, offset int) ([]entity.ConnectionEvent, error)) *MockConnectionStore_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxDone provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) MarkOutboxDone(eventID string) error {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxDone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_MarkOutboxDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxDone'
type MockConnectionStore_MarkOutboxDone_Call struct {
	*mock.Call
}

// MarkOutboxDone is a helper method to define mock.On call
//   - eventID string
func (_e *MockConnectionStore_Expecter) MarkOutboxDone(eventID interface{}) *MockConnectionStore_MarkOutboxDone_Call {
	return &MockConnectionStore_MarkOutboxDone_Call{Call: _e.mock.On("MarkOutboxDone", eventID)}
}

func (_c *MockConnectionStore_MarkOutboxDone_Call) Run(run func(eventID string)) *MockConnectionStore_MarkOutboxDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_MarkOutboxDone_Call) Return(err error) *MockConnectionStore_MarkOutboxDone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_MarkOutboxDone_Call) RunAndReturn(run func(eventID string) error) *MockConnectionStore_MarkOutboxDone_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxFailed provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) MarkOutboxFailed(eventID string, nextRetry time.Time) error {
	ret := _mock.Called(eventID, nextRetry)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) error); ok {
		r0 = returnFunc(eventID, nextRetry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_MarkOutboxFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxFailed'
type MockConnectionStore_MarkOutboxFailed_Call struct {
	*mock.Call
}

// MarkOutboxFailed is a helper method to define mock.On call
//   - eventID string
//   - nextRetry time.Time
func (_e *MockConnectionStore_Expecter) MarkOutboxFailed(eventID interface{}, nextRetry interface{}) *MockConnectionStore_MarkOutboxFailed_Call {
	return &MockConnectionStore_MarkOutboxFailed_Call{Call: _e.mock.On("MarkOutboxFailed", eventID, nextRetry)}
}

func (_c *MockConnectionStore_MarkOutboxFailed_Call) Run(run func(eventID string, nextRetry time.Time)) *MockConnectionStore_MarkOutboxFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionStore_MarkOutboxFailed_Call) Return(err error) *MockConnectionStore_MarkOutboxFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_MarkOutboxFailed_Call) RunAndReturn(run func(eventID string, nextRetry time.Time) error) *MockConnectionStore_MarkOutboxFailed_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) SoftDelete(tenantID string, infraType entity.InfraType, name string) error {
	ret := _mock.Called(tenantID, infraType, name)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.InfraType, string) error); ok {
		r0 = returnFunc(tenantID, infraType, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockConnectionStore_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - tenantID string
//   - infraType entity.InfraType
//   - name string
func (_e *MockConnectionStore_Expecter) SoftDelete(tenantID interface{}, infraType interface{}, name interface{}) *MockConnectionStore_SoftDelete_Call {
	return &MockConnectionStore_SoftDelete_Call{Call: _e.mock.On("SoftDelete", tenantID, infraType, name)}
}

func (_c *MockConnectionStore_SoftDelete_Call) Run(run func(tenantID string, infraType entity.InfraType, name string)) *MockConnectionStore_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.InfraType
		if args[1] != nil {
			arg1 = args[1].(entity.InfraType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionStore_SoftDelete_Call) Return(err error) *MockConnectionStore_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_SoftDelete_Call) RunAndReturn(run func(tenantID string, infraType entity.InfraType, name string) error) *MockConnectionStore_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) Upsert(info entity.ConnectionInfo) error {
	ret := _mock.Called(info)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(entity.ConnectionInfo) error); ok {
		r0 = returnFunc(info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockConnectionStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - info entity.ConnectionInfo
func (_e *MockConnectionStore_Expecter) Upsert(info interface{}) *MockConnectionStore_Upsert_Call {
	return &MockConnectionStore_Upsert_Call{Call: _e.mock.On("Upsert", info)}
}

func (_c *MockConnectionStore_Upsert_Call) Run(run func(info entity.ConnectionInfo)) *MockConnectionStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.ConnectionInfo
		if args[0] != nil {
			arg0 = args[0].(entity.ConnectionInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionStore_Upsert_Call) Return(err error) *MockConnectionStore_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_Upsert_Call) RunAndReturn(run func(info entity.ConnectionInfo) error) *MockConnectionStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
