apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
spec:
  addresses:
  # public ip same as ip range of docker because kind-cluster is deploy inside docker network
  - 172.18.0.10-172.18.0.100
  # - 127.0.0.1-127.0.0.100
  autoAssign: true

