apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-gateway
  labels:
    app: apisix-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix-gateway
  template:
    metadata:
      labels:
        app: apisix-gateway
    spec:
      containers:
        - name: apisix-gateway
          image: apache/apisix:3.12.0-debian
          ports:
            - containerPort: 9080
              name: http
            - containerPort: 9443
              name: https
            - containerPort: 9180
              name: admin
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
      volumes:
        - name: apisix-config
          configMap:
            name: apisix-config
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
spec:
  selector:
    app: apisix-gateway
  ports:
    - port: 9080
      name: http
      targetPort: 9080
    - port: 9443
      name: https
      targetPort: 9443
    - port: 9180
      name: admin
      targetPort: 9180
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_ipv6: false
      enable_control: true
      control:
        ip: "0.0.0.0"
        port: 9092
    deployment:
      admin:
        allow_admin:
          - 0.0.0.0/0
        admin_key:
          - name: "admin"
            key: edd1c9f034335f136f87ad84b625c8f1
            role: admin

          - name: "viewer"
            key: 4054f7cf07e344346cd3f287985e76a2
            role: viewer
      etcd:
        host:
          - "http://etcd-service:2379"
        prefix: "/apisix"
        timeout: 30
