// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumerGroupFactory creates a new instance of MockConsumerGroupFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerGroupFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerGroupFactory {
	mock := &MockConsumerGroupFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumerGroupFactory is an autogenerated mock type for the ConsumerGroupFactory type
type MockConsumerGroupFactory struct {
	mock.Mock
}

type MockConsumerGroupFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerGroupFactory) EXPECT() *MockConsumerGroupFactory_Expecter {
	return &MockConsumerGroupFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockConsumerGroupFactory
func (_mock *MockConsumerGroupFactory) New(groupID string) (sarama.ConsumerGroup, error) {
	ret := _mock.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 sarama.ConsumerGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (sarama.ConsumerGroup, error)); ok {
		return returnFunc(groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) sarama.ConsumerGroup); ok {
		r0 = returnFunc(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sarama.ConsumerGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConsumerGroupFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockConsumerGroupFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - groupID string
func (_e *MockConsumerGroupFactory_Expecter) New(groupID interface{}) *MockConsumerGroupFactory_New_Call {
	return &MockConsumerGroupFactory_New_Call{Call: _e.mock.On("New", groupID)}
}

func (_c *MockConsumerGroupFactory_New_Call) Run(run func(groupID string)) *MockConsumerGroupFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumerGroupFactory_New_Call) Return(consumerGroup sarama.ConsumerGroup, err error) *MockConsumerGroupFactory_New_Call {
	_c.Call.Return(consumerGroup, err)
	return _c
}

func (_c *MockConsumerGroupFactory_New_Call) RunAndReturn(run func(groupID string) (sarama.ConsumerGroup, error)) *MockConsumerGroupFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
