// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/backoffice/application/operations"
	"github.com/tuannm99/podzone/internal/backoffice/domain/order"
	"github.com/tuannm99/podzone/internal/backoffice/domain/routing"
)

// NewMockOrderRoutingUsecase creates a new instance of MockOrderRoutingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRoutingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRoutingUsecase {
	mock := &MockOrderRoutingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRoutingUsecase is an autogenerated mock type for the OrderRoutingUsecase type
type MockOrderRoutingUsecase struct {
	mock.Mock
}

type MockOrderRoutingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRoutingUsecase) EXPECT() *MockOrderRoutingUsecase_Expecter {
	return &MockOrderRoutingUsecase_Expecter{mock: &_m.Mock}
}

// AdvanceCustomerOrder provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) AdvanceCustomerOrder(ctx context.Context, cmd order.AdvanceCustomerOrderCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceCustomerOrder")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.AdvanceCustomerOrderCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.AdvanceCustomerOrderCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.AdvanceCustomerOrderCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_AdvanceCustomerOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceCustomerOrder'
type MockOrderRoutingUsecase_AdvanceCustomerOrder_Call struct {
	*mock.Call
}

// AdvanceCustomerOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd order.AdvanceCustomerOrderCmd
func (_e *MockOrderRoutingUsecase_Expecter) AdvanceCustomerOrder(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call {
	return &MockOrderRoutingUsecase_AdvanceCustomerOrder_Call{Call: _e.mock.On("AdvanceCustomerOrder", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call) Run(run func(ctx context.Context, cmd order.AdvanceCustomerOrderCmd)) *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.AdvanceCustomerOrderCmd
		if args[1] != nil {
			arg1 = args[1].(order.AdvanceCustomerOrderCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call) RunAndReturn(run func(ctx context.Context, cmd order.AdvanceCustomerOrderCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_AdvanceCustomerOrder_Call {
	_c.Call.Return(run)
	return _c
}

// AdvanceRoutedOrder provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) AdvanceRoutedOrder(ctx context.Context, storeID string, orderID string) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, storeID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceRoutedOrder")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, storeID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, storeID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, storeID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_AdvanceRoutedOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceRoutedOrder'
type MockOrderRoutingUsecase_AdvanceRoutedOrder_Call struct {
	*mock.Call
}

// AdvanceRoutedOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - orderID string
func (_e *MockOrderRoutingUsecase_Expecter) AdvanceRoutedOrder(ctx interface{}, storeID interface{}, orderID interface{}) *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call {
	return &MockOrderRoutingUsecase_AdvanceRoutedOrder_Call{Call: _e.mock.On("AdvanceRoutedOrder", ctx, storeID, orderID)}
}

func (_c *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call) Run(run func(ctx context.Context, storeID string, orderID string)) *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call) RunAndReturn(run func(ctx context.Context, storeID string, orderID string) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_AdvanceRoutedOrder_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdateOrders provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) BulkUpdateOrders(ctx context.Context, cmd order.BulkUpdateOrdersCmd) ([]routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateOrders")
	}

	var r0 []routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.BulkUpdateOrdersCmd) ([]routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.BulkUpdateOrdersCmd) []routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.BulkUpdateOrdersCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_BulkUpdateOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateOrders'
type MockOrderRoutingUsecase_BulkUpdateOrders_Call struct {
	*mock.Call
}

// BulkUpdateOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd order.BulkUpdateOrdersCmd
func (_e *MockOrderRoutingUsecase_Expecter) BulkUpdateOrders(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_BulkUpdateOrders_Call {
	return &MockOrderRoutingUsecase_BulkUpdateOrders_Call{Call: _e.mock.On("BulkUpdateOrders", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_BulkUpdateOrders_Call) Run(run func(ctx context.Context, cmd order.BulkUpdateOrdersCmd)) *MockOrderRoutingUsecase_BulkUpdateOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.BulkUpdateOrdersCmd
		if args[1] != nil {
			arg1 = args[1].(order.BulkUpdateOrdersCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_BulkUpdateOrders_Call) Return(routedOrders []routing.RoutedOrder, err error) *MockOrderRoutingUsecase_BulkUpdateOrders_Call {
	_c.Call.Return(routedOrders, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_BulkUpdateOrders_Call) RunAndReturn(run func(ctx context.Context, cmd order.BulkUpdateOrdersCmd) ([]routing.RoutedOrder, error)) *MockOrderRoutingUsecase_BulkUpdateOrders_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdateRoutedOrders provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) BulkUpdateRoutedOrders(ctx context.Context, cmd operations.BulkUpdateRoutedOrdersCmd) ([]routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateRoutedOrders")
	}

	var r0 []routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.BulkUpdateRoutedOrdersCmd) ([]routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.BulkUpdateRoutedOrdersCmd) []routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.BulkUpdateRoutedOrdersCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateRoutedOrders'
type MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call struct {
	*mock.Call
}

// BulkUpdateRoutedOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.BulkUpdateRoutedOrdersCmd
func (_e *MockOrderRoutingUsecase_Expecter) BulkUpdateRoutedOrders(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call {
	return &MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call{Call: _e.mock.On("BulkUpdateRoutedOrders", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call) Run(run func(ctx context.Context, cmd operations.BulkUpdateRoutedOrdersCmd)) *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.BulkUpdateRoutedOrdersCmd
		if args[1] != nil {
			arg1 = args[1].(operations.BulkUpdateRoutedOrdersCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call) Return(routedOrders []routing.RoutedOrder, err error) *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call {
	_c.Call.Return(routedOrders, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call) RunAndReturn(run func(ctx context.Context, cmd operations.BulkUpdateRoutedOrdersCmd) ([]routing.RoutedOrder, error)) *MockOrderRoutingUsecase_BulkUpdateRoutedOrders_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCustomerOrder provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) CreateCustomerOrder(ctx context.Context, cmd order.CreateCustomerOrderCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomerOrder")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.CreateCustomerOrderCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.CreateCustomerOrderCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.CreateCustomerOrderCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_CreateCustomerOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomerOrder'
type MockOrderRoutingUsecase_CreateCustomerOrder_Call struct {
	*mock.Call
}

// CreateCustomerOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd order.CreateCustomerOrderCmd
func (_e *MockOrderRoutingUsecase_Expecter) CreateCustomerOrder(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_CreateCustomerOrder_Call {
	return &MockOrderRoutingUsecase_CreateCustomerOrder_Call{Call: _e.mock.On("CreateCustomerOrder", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_CreateCustomerOrder_Call) Run(run func(ctx context.Context, cmd order.CreateCustomerOrderCmd)) *MockOrderRoutingUsecase_CreateCustomerOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.CreateCustomerOrderCmd
		if args[1] != nil {
			arg1 = args[1].(order.CreateCustomerOrderCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_CreateCustomerOrder_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_CreateCustomerOrder_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_CreateCustomerOrder_Call) RunAndReturn(run func(ctx context.Context, cmd order.CreateCustomerOrderCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_CreateCustomerOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoutedOrder provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) CreateRoutedOrder(ctx context.Context, cmd operations.CreateRoutedOrderCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoutedOrder")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateRoutedOrderCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateRoutedOrderCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.CreateRoutedOrderCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_CreateRoutedOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoutedOrder'
type MockOrderRoutingUsecase_CreateRoutedOrder_Call struct {
	*mock.Call
}

// CreateRoutedOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.CreateRoutedOrderCmd
func (_e *MockOrderRoutingUsecase_Expecter) CreateRoutedOrder(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_CreateRoutedOrder_Call {
	return &MockOrderRoutingUsecase_CreateRoutedOrder_Call{Call: _e.mock.On("CreateRoutedOrder", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_CreateRoutedOrder_Call) Run(run func(ctx context.Context, cmd operations.CreateRoutedOrderCmd)) *MockOrderRoutingUsecase_CreateRoutedOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.CreateRoutedOrderCmd
		if args[1] != nil {
			arg1 = args[1].(operations.CreateRoutedOrderCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_CreateRoutedOrder_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_CreateRoutedOrder_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_CreateRoutedOrder_Call) RunAndReturn(run func(ctx context.Context, cmd operations.CreateRoutedOrderCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_CreateRoutedOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ForceRerouteBlockedOrder provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) ForceRerouteBlockedOrder(ctx context.Context, cmd routing.ForceRerouteBlockedOrderCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ForceRerouteBlockedOrder")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.ForceRerouteBlockedOrderCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.ForceRerouteBlockedOrderCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, routing.ForceRerouteBlockedOrderCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceRerouteBlockedOrder'
type MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call struct {
	*mock.Call
}

// ForceRerouteBlockedOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd routing.ForceRerouteBlockedOrderCmd
func (_e *MockOrderRoutingUsecase_Expecter) ForceRerouteBlockedOrder(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call {
	return &MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call{Call: _e.mock.On("ForceRerouteBlockedOrder", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call) Run(run func(ctx context.Context, cmd routing.ForceRerouteBlockedOrderCmd)) *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 routing.ForceRerouteBlockedOrderCmd
		if args[1] != nil {
			arg1 = args[1].(routing.ForceRerouteBlockedOrderCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call) RunAndReturn(run func(ctx context.Context, cmd routing.ForceRerouteBlockedOrderCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_ForceRerouteBlockedOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ListCustomerOrders provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) ListCustomerOrders(ctx context.Context, query order.ListCustomerOrdersQuery) ([]routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomerOrders")
	}

	var r0 []routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.ListCustomerOrdersQuery) ([]routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.ListCustomerOrdersQuery) []routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.ListCustomerOrdersQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_ListCustomerOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCustomerOrders'
type MockOrderRoutingUsecase_ListCustomerOrders_Call struct {
	*mock.Call
}

// ListCustomerOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - query order.ListCustomerOrdersQuery
func (_e *MockOrderRoutingUsecase_Expecter) ListCustomerOrders(ctx interface{}, query interface{}) *MockOrderRoutingUsecase_ListCustomerOrders_Call {
	return &MockOrderRoutingUsecase_ListCustomerOrders_Call{Call: _e.mock.On("ListCustomerOrders", ctx, query)}
}

func (_c *MockOrderRoutingUsecase_ListCustomerOrders_Call) Run(run func(ctx context.Context, query order.ListCustomerOrdersQuery)) *MockOrderRoutingUsecase_ListCustomerOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.ListCustomerOrdersQuery
		if args[1] != nil {
			arg1 = args[1].(order.ListCustomerOrdersQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_ListCustomerOrders_Call) Return(routedOrders []routing.RoutedOrder, err error) *MockOrderRoutingUsecase_ListCustomerOrders_Call {
	_c.Call.Return(routedOrders, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_ListCustomerOrders_Call) RunAndReturn(run func(ctx context.Context, query order.ListCustomerOrdersQuery) ([]routing.RoutedOrder, error)) *MockOrderRoutingUsecase_ListCustomerOrders_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoutedOrderActivities provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) ListRoutedOrderActivities(ctx context.Context, query routing.RoutedOrderActivityFeedQuery) (*routing.RoutedOrderActivityFeedPage, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListRoutedOrderActivities")
	}

	var r0 *routing.RoutedOrderActivityFeedPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.RoutedOrderActivityFeedQuery) (*routing.RoutedOrderActivityFeedPage, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.RoutedOrderActivityFeedQuery) *routing.RoutedOrderActivityFeedPage); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrderActivityFeedPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, routing.RoutedOrderActivityFeedQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_ListRoutedOrderActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoutedOrderActivities'
type MockOrderRoutingUsecase_ListRoutedOrderActivities_Call struct {
	*mock.Call
}

// ListRoutedOrderActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - query routing.RoutedOrderActivityFeedQuery
func (_e *MockOrderRoutingUsecase_Expecter) ListRoutedOrderActivities(ctx interface{}, query interface{}) *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call {
	return &MockOrderRoutingUsecase_ListRoutedOrderActivities_Call{Call: _e.mock.On("ListRoutedOrderActivities", ctx, query)}
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call) Run(run func(ctx context.Context, query routing.RoutedOrderActivityFeedQuery)) *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 routing.RoutedOrderActivityFeedQuery
		if args[1] != nil {
			arg1 = args[1].(routing.RoutedOrderActivityFeedQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call) Return(routedOrderActivityFeedPage *routing.RoutedOrderActivityFeedPage, err error) *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call {
	_c.Call.Return(routedOrderActivityFeedPage, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call) RunAndReturn(run func(ctx context.Context, query routing.RoutedOrderActivityFeedQuery) (*routing.RoutedOrderActivityFeedPage, error)) *MockOrderRoutingUsecase_ListRoutedOrderActivities_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoutedOrders provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) ListRoutedOrders(ctx context.Context, query operations.ListRoutedOrdersQuery) ([]routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListRoutedOrders")
	}

	var r0 []routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListRoutedOrdersQuery) ([]routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListRoutedOrdersQuery) []routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListRoutedOrdersQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_ListRoutedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoutedOrders'
type MockOrderRoutingUsecase_ListRoutedOrders_Call struct {
	*mock.Call
}

// ListRoutedOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - query operations.ListRoutedOrdersQuery
func (_e *MockOrderRoutingUsecase_Expecter) ListRoutedOrders(ctx interface{}, query interface{}) *MockOrderRoutingUsecase_ListRoutedOrders_Call {
	return &MockOrderRoutingUsecase_ListRoutedOrders_Call{Call: _e.mock.On("ListRoutedOrders", ctx, query)}
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrders_Call) Run(run func(ctx context.Context, query operations.ListRoutedOrdersQuery)) *MockOrderRoutingUsecase_ListRoutedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListRoutedOrdersQuery
		if args[1] != nil {
			arg1 = args[1].(operations.ListRoutedOrdersQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrders_Call) Return(routedOrders []routing.RoutedOrder, err error) *MockOrderRoutingUsecase_ListRoutedOrders_Call {
	_c.Call.Return(routedOrders, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_ListRoutedOrders_Call) RunAndReturn(run func(ctx context.Context, query operations.ListRoutedOrdersQuery) ([]routing.RoutedOrder, error)) *MockOrderRoutingUsecase_ListRoutedOrders_Call {
	_c.Call.Return(run)
	return _c
}

// OpenOrderException provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) OpenOrderException(ctx context.Context, cmd operations.OpenOrderExceptionCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for OpenOrderException")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.OpenOrderExceptionCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.OpenOrderExceptionCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.OpenOrderExceptionCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_OpenOrderException_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenOrderException'
type MockOrderRoutingUsecase_OpenOrderException_Call struct {
	*mock.Call
}

// OpenOrderException is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.OpenOrderExceptionCmd
func (_e *MockOrderRoutingUsecase_Expecter) OpenOrderException(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_OpenOrderException_Call {
	return &MockOrderRoutingUsecase_OpenOrderException_Call{Call: _e.mock.On("OpenOrderException", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_OpenOrderException_Call) Run(run func(ctx context.Context, cmd operations.OpenOrderExceptionCmd)) *MockOrderRoutingUsecase_OpenOrderException_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.OpenOrderExceptionCmd
		if args[1] != nil {
			arg1 = args[1].(operations.OpenOrderExceptionCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_OpenOrderException_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_OpenOrderException_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_OpenOrderException_Call) RunAndReturn(run func(ctx context.Context, cmd operations.OpenOrderExceptionCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_OpenOrderException_Call {
	_c.Call.Return(run)
	return _c
}

// RecommendRoutedOrderPartner provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) RecommendRoutedOrderPartner(ctx context.Context, query routing.RecommendRoutedOrderPartnerQuery) (*routing.RoutedOrderRecommendation, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for RecommendRoutedOrderPartner")
	}

	var r0 *routing.RoutedOrderRecommendation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.RecommendRoutedOrderPartnerQuery) (*routing.RoutedOrderRecommendation, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, routing.RecommendRoutedOrderPartnerQuery) *routing.RoutedOrderRecommendation); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrderRecommendation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, routing.RecommendRoutedOrderPartnerQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecommendRoutedOrderPartner'
type MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call struct {
	*mock.Call
}

// RecommendRoutedOrderPartner is a helper method to define mock.On call
//   - ctx context.Context
//   - query routing.RecommendRoutedOrderPartnerQuery
func (_e *MockOrderRoutingUsecase_Expecter) RecommendRoutedOrderPartner(ctx interface{}, query interface{}) *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call {
	return &MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call{Call: _e.mock.On("RecommendRoutedOrderPartner", ctx, query)}
}

func (_c *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call) Run(run func(ctx context.Context, query routing.RecommendRoutedOrderPartnerQuery)) *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 routing.RecommendRoutedOrderPartnerQuery
		if args[1] != nil {
			arg1 = args[1].(routing.RecommendRoutedOrderPartnerQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call) Return(routedOrderRecommendation *routing.RoutedOrderRecommendation, err error) *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call {
	_c.Call.Return(routedOrderRecommendation, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call) RunAndReturn(run func(ctx context.Context, query routing.RecommendRoutedOrderPartnerQuery) (*routing.RoutedOrderRecommendation, error)) *MockOrderRoutingUsecase_RecommendRoutedOrderPartner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderExceptionStatus provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) UpdateOrderExceptionStatus(ctx context.Context, cmd operations.UpdateOrderExceptionStatusCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderExceptionStatus")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderExceptionStatusCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderExceptionStatusCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateOrderExceptionStatusCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderExceptionStatus'
type MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call struct {
	*mock.Call
}

// UpdateOrderExceptionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.UpdateOrderExceptionStatusCmd
func (_e *MockOrderRoutingUsecase_Expecter) UpdateOrderExceptionStatus(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call {
	return &MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call{Call: _e.mock.On("UpdateOrderExceptionStatus", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call) Run(run func(ctx context.Context, cmd operations.UpdateOrderExceptionStatusCmd)) *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateOrderExceptionStatusCmd
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateOrderExceptionStatusCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call) RunAndReturn(run func(ctx context.Context, cmd operations.UpdateOrderExceptionStatusCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_UpdateOrderExceptionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderIssueHandling provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) UpdateOrderIssueHandling(ctx context.Context, cmd operations.UpdateOrderIssueHandlingCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderIssueHandling")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderIssueHandlingCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderIssueHandlingCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateOrderIssueHandlingCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderIssueHandling'
type MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call struct {
	*mock.Call
}

// UpdateOrderIssueHandling is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.UpdateOrderIssueHandlingCmd
func (_e *MockOrderRoutingUsecase_Expecter) UpdateOrderIssueHandling(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call {
	return &MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call{Call: _e.mock.On("UpdateOrderIssueHandling", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call) Run(run func(ctx context.Context, cmd operations.UpdateOrderIssueHandlingCmd)) *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateOrderIssueHandlingCmd
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateOrderIssueHandlingCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call) RunAndReturn(run func(ctx context.Context, cmd operations.UpdateOrderIssueHandlingCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_UpdateOrderIssueHandling_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderQueueControl provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) UpdateOrderQueueControl(ctx context.Context, cmd operations.UpdateOrderQueueControlCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderQueueControl")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderQueueControlCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderQueueControlCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateOrderQueueControlCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_UpdateOrderQueueControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderQueueControl'
type MockOrderRoutingUsecase_UpdateOrderQueueControl_Call struct {
	*mock.Call
}

// UpdateOrderQueueControl is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.UpdateOrderQueueControlCmd
func (_e *MockOrderRoutingUsecase_Expecter) UpdateOrderQueueControl(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call {
	return &MockOrderRoutingUsecase_UpdateOrderQueueControl_Call{Call: _e.mock.On("UpdateOrderQueueControl", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call) Run(run func(ctx context.Context, cmd operations.UpdateOrderQueueControlCmd)) *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateOrderQueueControlCmd
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateOrderQueueControlCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call) RunAndReturn(run func(ctx context.Context, cmd operations.UpdateOrderQueueControlCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_UpdateOrderQueueControl_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderSettlement provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) UpdateOrderSettlement(ctx context.Context, cmd operations.UpdateOrderSettlementCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderSettlement")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderSettlementCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderSettlementCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateOrderSettlementCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_UpdateOrderSettlement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderSettlement'
type MockOrderRoutingUsecase_UpdateOrderSettlement_Call struct {
	*mock.Call
}

// UpdateOrderSettlement is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.UpdateOrderSettlementCmd
func (_e *MockOrderRoutingUsecase_Expecter) UpdateOrderSettlement(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_UpdateOrderSettlement_Call {
	return &MockOrderRoutingUsecase_UpdateOrderSettlement_Call{Call: _e.mock.On("UpdateOrderSettlement", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_UpdateOrderSettlement_Call) Run(run func(ctx context.Context, cmd operations.UpdateOrderSettlementCmd)) *MockOrderRoutingUsecase_UpdateOrderSettlement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateOrderSettlementCmd
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateOrderSettlementCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderSettlement_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_UpdateOrderSettlement_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderSettlement_Call) RunAndReturn(run func(ctx context.Context, cmd operations.UpdateOrderSettlementCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_UpdateOrderSettlement_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderShipment provides a mock function for the type MockOrderRoutingUsecase
func (_mock *MockOrderRoutingUsecase) UpdateOrderShipment(ctx context.Context, cmd operations.UpdateOrderShipmentCmd) (*routing.RoutedOrder, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderShipment")
	}

	var r0 *routing.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderShipmentCmd) (*routing.RoutedOrder, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateOrderShipmentCmd) *routing.RoutedOrder); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateOrderShipmentCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingUsecase_UpdateOrderShipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderShipment'
type MockOrderRoutingUsecase_UpdateOrderShipment_Call struct {
	*mock.Call
}

// UpdateOrderShipment is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd operations.UpdateOrderShipmentCmd
func (_e *MockOrderRoutingUsecase_Expecter) UpdateOrderShipment(ctx interface{}, cmd interface{}) *MockOrderRoutingUsecase_UpdateOrderShipment_Call {
	return &MockOrderRoutingUsecase_UpdateOrderShipment_Call{Call: _e.mock.On("UpdateOrderShipment", ctx, cmd)}
}

func (_c *MockOrderRoutingUsecase_UpdateOrderShipment_Call) Run(run func(ctx context.Context, cmd operations.UpdateOrderShipmentCmd)) *MockOrderRoutingUsecase_UpdateOrderShipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateOrderShipmentCmd
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateOrderShipmentCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderShipment_Call) Return(routedOrder *routing.RoutedOrder, err error) *MockOrderRoutingUsecase_UpdateOrderShipment_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingUsecase_UpdateOrderShipment_Call) RunAndReturn(run func(ctx context.Context, cmd operations.UpdateOrderShipmentCmd) (*routing.RoutedOrder, error)) *MockOrderRoutingUsecase_UpdateOrderShipment_Call {
	_c.Call.Return(run)
	return _c
}
