// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKVStore creates a new instance of MockKVStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKVStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKVStore {
	mock := &MockKVStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKVStore is an autogenerated mock type for the KVStore type
type MockKVStore struct {
	mock.Mock
}

type MockKVStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKVStore) EXPECT() *MockKVStore_Expecter {
	return &MockKVStore_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockKVStore
func (_mock *MockKVStore) Del(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVStore_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockKVStore_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockKVStore_Expecter) Del(ctx interface{}, path interface{}) *MockKVStore_Del_Call {
	return &MockKVStore_Del_Call{Call: _e.mock.On("Del", ctx, path)}
}

func (_c *MockKVStore_Del_Call) Run(run func(ctx context.Context, path string)) *MockKVStore_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockKVStore_Del_Call) Return(err error) *MockKVStore_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVStore_Del_Call) RunAndReturn(run func(context.Context, string) error) *MockKVStore_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKVStore
func (_mock *MockKVStore) Get(ctx context.Context, path string) ([]byte, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKVStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockKVStore_Expecter) Get(ctx interface{}, path interface{}) *MockKVStore_Get_Call {
	return &MockKVStore_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockKVStore_Get_Call) Run(run func(ctx context.Context, path string)) *MockKVStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockKVStore_Get_Call) Return(bytes []byte, err error) *MockKVStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKVStore_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockKVStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetKVs provides a mock function for the type MockKVStore
func (_mock *MockKVStore) GetKVs(ctx context.Context, prefix string) (map[string][]byte, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetKVs")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string][]byte, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string][]byte); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKVStore_GetKVs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKVs'
type MockKVStore_GetKVs_Call struct {
	*mock.Call
}

// GetKVs is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockKVStore_Expecter) GetKVs(ctx interface{}, prefix interface{}) *MockKVStore_GetKVs_Call {
	return &MockKVStore_GetKVs_Call{Call: _e.mock.On("GetKVs", ctx, prefix)}
}

func (_c *MockKVStore_GetKVs_Call) Run(run func(ctx context.Context, prefix string)) *MockKVStore_GetKVs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockKVStore_GetKVs_Call) Return(stringToBytes map[string][]byte, err error) *MockKVStore_GetKVs_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockKVStore_GetKVs_Call) RunAndReturn(run func(context.Context, string) (map[string][]byte, error)) *MockKVStore_GetKVs_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockKVStore
func (_mock *MockKVStore) Put(ctx context.Context, path string, value []byte) error {
	ret := _mock.Called(ctx, path, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, path, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKVStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockKVStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - value []byte
func (_e *MockKVStore_Expecter) Put(ctx interface{}, path interface{}, value interface{}) *MockKVStore_Put_Call {
	return &MockKVStore_Put_Call{Call: _e.mock.On("Put", ctx, path, value)}
}

func (_c *MockKVStore_Put_Call) Run(run func(ctx context.Context, path string, value []byte)) *MockKVStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockKVStore_Put_Call) Return(err error) *MockKVStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKVStore_Put_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockKVStore_Put_Call {
	_c.Call.Return(run)
	return _c
}
