// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTenantBootstrapper creates a new instance of MockTenantBootstrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantBootstrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantBootstrapper {
	mock := &MockTenantBootstrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTenantBootstrapper is an autogenerated mock type for the TenantBootstrapper type
type MockTenantBootstrapper struct {
	mock.Mock
}

type MockTenantBootstrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantBootstrapper) EXPECT() *MockTenantBootstrapper_Expecter {
	return &MockTenantBootstrapper_Expecter{mock: &_m.Mock}
}

// EnsureReady provides a mock function for the type MockTenantBootstrapper
func (_mock *MockTenantBootstrapper) EnsureReady(ctx context.Context, tenantID string) error {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTenantBootstrapper_EnsureReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureReady'
type MockTenantBootstrapper_EnsureReady_Call struct {
	*mock.Call
}

// EnsureReady is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockTenantBootstrapper_Expecter) EnsureReady(ctx interface{}, tenantID interface{}) *MockTenantBootstrapper_EnsureReady_Call {
	return &MockTenantBootstrapper_EnsureReady_Call{Call: _e.mock.On("EnsureReady", ctx, tenantID)}
}

func (_c *MockTenantBootstrapper_EnsureReady_Call) Run(run func(ctx context.Context, tenantID string)) *MockTenantBootstrapper_EnsureReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantBootstrapper_EnsureReady_Call) Return(err error) *MockTenantBootstrapper_EnsureReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTenantBootstrapper_EnsureReady_Call) RunAndReturn(run func(ctx context.Context, tenantID string) error) *MockTenantBootstrapper_EnsureReady_Call {
	_c.Call.Return(run)
	return _c
}
