logger:
  app_name: 'podzone_admin_iam'
  provider: 'zap'
  level: 'debug'
  env: 'dev'

sql:
  auth:
    uri: '${PG_AUTH_DSN}'
    provider: postgres
    should_run_migration: false

grpc:
  port: 50053

pprof:
  enable: true
  addr: '127.0.0.1:6060'
