// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: partner/v1/partner.proto

package pbpartnerv1

import (
	v1 "github.com/tuannm99/podzone/pkg/api/proto/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingCostRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Cost          string                 `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingCostRule) Reset() {
	*x = ShippingCostRule{}
	mi := &file_partner_v1_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostRule) ProtoMessage() {}

func (x *ShippingCostRule) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostRule.ProtoReflect.Descriptor instead.
func (*ShippingCostRule) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingCostRule) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ShippingCostRule) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

type Partner struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId              string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Code                  string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name                  string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ContactName           string                 `protobuf:"bytes,5,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactEmail          string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Notes                 string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	PartnerType           string                 `protobuf:"bytes,8,opt,name=partner_type,json=partnerType,proto3" json:"partner_type,omitempty"`
	Status                string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SupportedProductTypes []string               `protobuf:"bytes,12,rep,name=supported_product_types,json=supportedProductTypes,proto3" json:"supported_product_types,omitempty"`
	SupportedRegions      []string               `protobuf:"bytes,13,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	SlaDays               int32                  `protobuf:"varint,14,opt,name=sla_days,json=slaDays,proto3" json:"sla_days,omitempty"`
	RoutingPriority       int32                  `protobuf:"varint,15,opt,name=routing_priority,json=routingPriority,proto3" json:"routing_priority,omitempty"`
	BaseFulfillmentCost   string                 `protobuf:"bytes,16,opt,name=base_fulfillment_cost,json=baseFulfillmentCost,proto3" json:"base_fulfillment_cost,omitempty"`
	ShippingCostRules     []*ShippingCostRule    `protobuf:"bytes,17,rep,name=shipping_cost_rules,json=shippingCostRules,proto3" json:"shipping_cost_rules,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Partner) Reset() {
	*x = Partner{}
	mi := &file_partner_v1_partner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partner) ProtoMessage() {}

func (x *Partner) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partner.ProtoReflect.Descriptor instead.
func (*Partner) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{1}
}

func (x *Partner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Partner) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Partner) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Partner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Partner) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Partner) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Partner) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Partner) GetPartnerType() string {
	if x != nil {
		return x.PartnerType
	}
	return ""
}

func (x *Partner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Partner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Partner) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Partner) GetSupportedProductTypes() []string {
	if x != nil {
		return x.SupportedProductTypes
	}
	return nil
}

func (x *Partner) GetSupportedRegions() []string {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *Partner) GetSlaDays() int32 {
	if x != nil {
		return x.SlaDays
	}
	return 0
}

func (x *Partner) GetRoutingPriority() int32 {
	if x != nil {
		return x.RoutingPriority
	}
	return 0
}

func (x *Partner) GetBaseFulfillmentCost() string {
	if x != nil {
		return x.BaseFulfillmentCost
	}
	return ""
}

func (x *Partner) GetShippingCostRules() []*ShippingCostRule {
	if x != nil {
		return x.ShippingCostRules
	}
	return nil
}

type CreatePartnerRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TenantId              string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Code                  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ContactName           string                 `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactEmail          string                 `protobuf:"bytes,5,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Notes                 string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	PartnerType           string                 `protobuf:"bytes,7,opt,name=partner_type,json=partnerType,proto3" json:"partner_type,omitempty"`
	SupportedProductTypes []string               `protobuf:"bytes,8,rep,name=supported_product_types,json=supportedProductTypes,proto3" json:"supported_product_types,omitempty"`
	SupportedRegions      []string               `protobuf:"bytes,9,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	SlaDays               int32                  `protobuf:"varint,10,opt,name=sla_days,json=slaDays,proto3" json:"sla_days,omitempty"`
	RoutingPriority       int32                  `protobuf:"varint,11,opt,name=routing_priority,json=routingPriority,proto3" json:"routing_priority,omitempty"`
	BaseFulfillmentCost   string                 `protobuf:"bytes,12,opt,name=base_fulfillment_cost,json=baseFulfillmentCost,proto3" json:"base_fulfillment_cost,omitempty"`
	ShippingCostRules     []*ShippingCostRule    `protobuf:"bytes,13,rep,name=shipping_cost_rules,json=shippingCostRules,proto3" json:"shipping_cost_rules,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreatePartnerRequest) Reset() {
	*x = CreatePartnerRequest{}
	mi := &file_partner_v1_partner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartnerRequest) ProtoMessage() {}

func (x *CreatePartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartnerRequest.ProtoReflect.Descriptor instead.
func (*CreatePartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePartnerRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreatePartnerRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePartnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePartnerRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *CreatePartnerRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *CreatePartnerRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreatePartnerRequest) GetPartnerType() string {
	if x != nil {
		return x.PartnerType
	}
	return ""
}

func (x *CreatePartnerRequest) GetSupportedProductTypes() []string {
	if x != nil {
		return x.SupportedProductTypes
	}
	return nil
}

func (x *CreatePartnerRequest) GetSupportedRegions() []string {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *CreatePartnerRequest) GetSlaDays() int32 {
	if x != nil {
		return x.SlaDays
	}
	return 0
}

func (x *CreatePartnerRequest) GetRoutingPriority() int32 {
	if x != nil {
		return x.RoutingPriority
	}
	return 0
}

func (x *CreatePartnerRequest) GetBaseFulfillmentCost() string {
	if x != nil {
		return x.BaseFulfillmentCost
	}
	return ""
}

func (x *CreatePartnerRequest) GetShippingCostRules() []*ShippingCostRule {
	if x != nil {
		return x.ShippingCostRules
	}
	return nil
}

type GetPartnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartnerRequest) Reset() {
	*x = GetPartnerRequest{}
	mi := &file_partner_v1_partner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerRequest) ProtoMessage() {}

func (x *GetPartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerRequest.ProtoReflect.Descriptor instead.
func (*GetPartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{3}
}

func (x *GetPartnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPartnersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PartnerType   string                 `protobuf:"bytes,3,opt,name=partner_type,json=partnerType,proto3" json:"partner_type,omitempty"`
	Collection    *v1.CollectionRequest  `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartnersRequest) Reset() {
	*x = ListPartnersRequest{}
	mi := &file_partner_v1_partner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartnersRequest) ProtoMessage() {}

func (x *ListPartnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartnersRequest.ProtoReflect.Descriptor instead.
func (*ListPartnersRequest) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{4}
}

func (x *ListPartnersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListPartnersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPartnersRequest) GetPartnerType() string {
	if x != nil {
		return x.PartnerType
	}
	return ""
}

func (x *ListPartnersRequest) GetCollection() *v1.CollectionRequest {
	if x != nil {
		return x.Collection
	}
	return nil
}

type ListPartnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partners      []*Partner             `protobuf:"bytes,1,rep,name=partners,proto3" json:"partners,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartnersResponse) Reset() {
	*x = ListPartnersResponse{}
	mi := &file_partner_v1_partner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartnersResponse) ProtoMessage() {}

func (x *ListPartnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartnersResponse.ProtoReflect.Descriptor instead.
func (*ListPartnersResponse) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{5}
}

func (x *ListPartnersResponse) GetPartners() []*Partner {
	if x != nil {
		return x.Partners
	}
	return nil
}

func (x *ListPartnersResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type UpdatePartnerRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContactName           string                 `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactEmail          string                 `protobuf:"bytes,4,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Notes                 string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	PartnerType           string                 `protobuf:"bytes,6,opt,name=partner_type,json=partnerType,proto3" json:"partner_type,omitempty"`
	SupportedProductTypes []string               `protobuf:"bytes,7,rep,name=supported_product_types,json=supportedProductTypes,proto3" json:"supported_product_types,omitempty"`
	SupportedRegions      []string               `protobuf:"bytes,8,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	SlaDays               int32                  `protobuf:"varint,9,opt,name=sla_days,json=slaDays,proto3" json:"sla_days,omitempty"`
	RoutingPriority       int32                  `protobuf:"varint,10,opt,name=routing_priority,json=routingPriority,proto3" json:"routing_priority,omitempty"`
	BaseFulfillmentCost   string                 `protobuf:"bytes,11,opt,name=base_fulfillment_cost,json=baseFulfillmentCost,proto3" json:"base_fulfillment_cost,omitempty"`
	ShippingCostRules     []*ShippingCostRule    `protobuf:"bytes,12,rep,name=shipping_cost_rules,json=shippingCostRules,proto3" json:"shipping_cost_rules,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdatePartnerRequest) Reset() {
	*x = UpdatePartnerRequest{}
	mi := &file_partner_v1_partner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerRequest) ProtoMessage() {}

func (x *UpdatePartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartnerRequest) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePartnerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePartnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePartnerRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *UpdatePartnerRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdatePartnerRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdatePartnerRequest) GetPartnerType() string {
	if x != nil {
		return x.PartnerType
	}
	return ""
}

func (x *UpdatePartnerRequest) GetSupportedProductTypes() []string {
	if x != nil {
		return x.SupportedProductTypes
	}
	return nil
}

func (x *UpdatePartnerRequest) GetSupportedRegions() []string {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *UpdatePartnerRequest) GetSlaDays() int32 {
	if x != nil {
		return x.SlaDays
	}
	return 0
}

func (x *UpdatePartnerRequest) GetRoutingPriority() int32 {
	if x != nil {
		return x.RoutingPriority
	}
	return 0
}

func (x *UpdatePartnerRequest) GetBaseFulfillmentCost() string {
	if x != nil {
		return x.BaseFulfillmentCost
	}
	return ""
}

func (x *UpdatePartnerRequest) GetShippingCostRules() []*ShippingCostRule {
	if x != nil {
		return x.ShippingCostRules
	}
	return nil
}

type UpdatePartnerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePartnerStatusRequest) Reset() {
	*x = UpdatePartnerStatusRequest{}
	mi := &file_partner_v1_partner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartnerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartnerStatusRequest) ProtoMessage() {}

func (x *UpdatePartnerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_v1_partner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartnerStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartnerStatusRequest) Descriptor() ([]byte, []int) {
	return file_partner_v1_partner_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePartnerStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePartnerStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_partner_v1_partner_proto protoreflect.FileDescriptor

const file_partner_v1_partner_proto_rawDesc = "" +
	"\n" +
	"\x18partner/v1/partner.proto\x12\apartner\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\">\n" +
	"\x10ShippingCostRule\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\tR\x04cost\"\x97\x05\n" +
	"\aPartner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x05 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12!\n" +
	"\fpartner_type\x18\b \x01(\tR\vpartnerType\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\x17supported_product_types\x18\f \x03(\tR\x15supportedProductTypes\x12+\n" +
	"\x11supported_regions\x18\r \x03(\tR\x10supportedRegions\x12\x19\n" +
	"\bsla_days\x18\x0e \x01(\x05R\aslaDays\x12)\n" +
	"\x10routing_priority\x18\x0f \x01(\x05R\x0froutingPriority\x122\n" +
	"\x15base_fulfillment_cost\x18\x10 \x01(\tR\x13baseFulfillmentCost\x12I\n" +
	"\x13shipping_cost_rules\x18\x11 \x03(\v2\x19.partner.ShippingCostRuleR\x11shippingCostRules\"\x86\x04\n" +
	"\x14CreatePartnerRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x04 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\x05 \x01(\tR\fcontactEmail\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12!\n" +
	"\fpartner_type\x18\a \x01(\tR\vpartnerType\x126\n" +
	"\x17supported_product_types\x18\b \x03(\tR\x15supportedProductTypes\x12+\n" +
	"\x11supported_regions\x18\t \x03(\tR\x10supportedRegions\x12\x19\n" +
	"\bsla_days\x18\n" +
	" \x01(\x05R\aslaDays\x12)\n" +
	"\x10routing_priority\x18\v \x01(\x05R\x0froutingPriority\x122\n" +
	"\x15base_fulfillment_cost\x18\f \x01(\tR\x13baseFulfillmentCost\x12I\n" +
	"\x13shipping_cost_rules\x18\r \x03(\v2\x19.partner.ShippingCostRuleR\x11shippingCostRules\"#\n" +
	"\x11GetPartnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa8\x01\n" +
	"\x13ListPartnersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fpartner_type\x18\x03 \x01(\tR\vpartnerType\x129\n" +
	"\n" +
	"collection\x18\x04 \x01(\v2\x19.common.CollectionRequestR\n" +
	"collection\"s\n" +
	"\x14ListPartnersResponse\x12,\n" +
	"\bpartners\x18\x01 \x03(\v2\x10.partner.PartnerR\bpartners\x12-\n" +
	"\tpage_info\x18\x02 \x01(\v2\x10.common.PageInfoR\bpageInfo\"\xe5\x03\n" +
	"\x14UpdatePartnerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\x04 \x01(\tR\fcontactEmail\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12!\n" +
	"\fpartner_type\x18\x06 \x01(\tR\vpartnerType\x126\n" +
	"\x17supported_product_types\x18\a \x03(\tR\x15supportedProductTypes\x12+\n" +
	"\x11supported_regions\x18\b \x03(\tR\x10supportedRegions\x12\x19\n" +
	"\bsla_days\x18\t \x01(\x05R\aslaDays\x12)\n" +
	"\x10routing_priority\x18\n" +
	" \x01(\x05R\x0froutingPriority\x122\n" +
	"\x15base_fulfillment_cost\x18\v \x01(\tR\x13baseFulfillmentCost\x12I\n" +
	"\x13shipping_cost_rules\x18\f \x03(\v2\x19.partner.ShippingCostRuleR\x11shippingCostRules\"D\n" +
	"\x1aUpdatePartnerStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa0\x04\n" +
	"\x0ePartnerService\x12a\n" +
	"\rCreatePartner\x12\x1d.partner.CreatePartnerRequest\x1a\x10.partner.Partner\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/partner/v1/partners\x12]\n" +
	"\n" +
	"GetPartner\x12\x1a.partner.GetPartnerRequest\x1a\x10.partner.Partner\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/partner/v1/partners/{id}\x12i\n" +
	"\fListPartners\x12\x1c.partner.ListPartnersRequest\x1a\x1d.partner.ListPartnersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/partner/v1/partners\x12f\n" +
	"\rUpdatePartner\x12\x1d.partner.UpdatePartnerRequest\x1a\x10.partner.Partner\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/partner/v1/partners/{id}\x12y\n" +
	"\x13UpdatePartnerStatus\x12#.partner.UpdatePartnerStatusRequest\x1a\x10.partner.Partner\"+\x82\xd3\xe4\x93\x02%:\x01*2 /partner/v1/partners/{id}/statusBBZ@github.com/tuannm99/podzone/pkg/api/proto/partner/v1;pbpartnerv1b\x06proto3"

var (
	file_partner_v1_partner_proto_rawDescOnce sync.Once
	file_partner_v1_partner_proto_rawDescData []byte
)

func file_partner_v1_partner_proto_rawDescGZIP() []byte {
	file_partner_v1_partner_proto_rawDescOnce.Do(func() {
		file_partner_v1_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partner_v1_partner_proto_rawDesc), len(file_partner_v1_partner_proto_rawDesc)))
	})
	return file_partner_v1_partner_proto_rawDescData
}

var file_partner_v1_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_partner_v1_partner_proto_goTypes = []any{
	(*ShippingCostRule)(nil),           // 0: partner.ShippingCostRule
	(*Partner)(nil),                    // 1: partner.Partner
	(*CreatePartnerRequest)(nil),       // 2: partner.CreatePartnerRequest
	(*GetPartnerRequest)(nil),          // 3: partner.GetPartnerRequest
	(*ListPartnersRequest)(nil),        // 4: partner.ListPartnersRequest
	(*ListPartnersResponse)(nil),       // 5: partner.ListPartnersResponse
	(*UpdatePartnerRequest)(nil),       // 6: partner.UpdatePartnerRequest
	(*UpdatePartnerStatusRequest)(nil), // 7: partner.UpdatePartnerStatusRequest
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
	(*v1.CollectionRequest)(nil),       // 9: common.CollectionRequest
	(*v1.PageInfo)(nil),                // 10: common.PageInfo
}
var file_partner_v1_partner_proto_depIdxs = []int32{
	8,  // 0: partner.Partner.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: partner.Partner.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: partner.Partner.shipping_cost_rules:type_name -> partner.ShippingCostRule
	0,  // 3: partner.CreatePartnerRequest.shipping_cost_rules:type_name -> partner.ShippingCostRule
	9,  // 4: partner.ListPartnersRequest.collection:type_name -> common.CollectionRequest
	1,  // 5: partner.ListPartnersResponse.partners:type_name -> partner.Partner
	10, // 6: partner.ListPartnersResponse.page_info:type_name -> common.PageInfo
	0,  // 7: partner.UpdatePartnerRequest.shipping_cost_rules:type_name -> partner.ShippingCostRule
	2,  // 8: partner.PartnerService.CreatePartner:input_type -> partner.CreatePartnerRequest
	3,  // 9: partner.PartnerService.GetPartner:input_type -> partner.GetPartnerRequest
	4,  // 10: partner.PartnerService.ListPartners:input_type -> partner.ListPartnersRequest
	6,  // 11: partner.PartnerService.UpdatePartner:input_type -> partner.UpdatePartnerRequest
	7,  // 12: partner.PartnerService.UpdatePartnerStatus:input_type -> partner.UpdatePartnerStatusRequest
	1,  // 13: partner.PartnerService.CreatePartner:output_type -> partner.Partner
	1,  // 14: partner.PartnerService.GetPartner:output_type -> partner.Partner
	5,  // 15: partner.PartnerService.ListPartners:output_type -> partner.ListPartnersResponse
	1,  // 16: partner.PartnerService.UpdatePartner:output_type -> partner.Partner
	1,  // 17: partner.PartnerService.UpdatePartnerStatus:output_type -> partner.Partner
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_partner_v1_partner_proto_init() }
func file_partner_v1_partner_proto_init() {
	if File_partner_v1_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partner_v1_partner_proto_rawDesc), len(file_partner_v1_partner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_partner_v1_partner_proto_goTypes,
		DependencyIndexes: file_partner_v1_partner_proto_depIdxs,
		MessageInfos:      file_partner_v1_partner_proto_msgTypes,
	}.Build()
	File_partner_v1_partner_proto = out.File
	file_partner_v1_partner_proto_goTypes = nil
	file_partner_v1_partner_proto_depIdxs = nil
}
