// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAMProjectionRepository creates a new instance of MockIAMProjectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAMProjectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAMProjectionRepository {
	mock := &MockIAMProjectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAMProjectionRepository is an autogenerated mock type for the IAMProjectionRepository type
type MockIAMProjectionRepository struct {
	mock.Mock
}

type MockIAMProjectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAMProjectionRepository) EXPECT() *MockIAMProjectionRepository_Expecter {
	return &MockIAMProjectionRepository_Expecter{mock: &_m.Mock}
}

// UpsertTenant provides a mock function for the type MockIAMProjectionRepository
func (_mock *MockIAMProjectionRepository) UpsertTenant(ctx context.Context, tenantID string, slug string, name string) error {
	ret := _mock.Called(ctx, tenantID, slug, name)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTenant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, slug, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAMProjectionRepository_UpsertTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTenant'
type MockIAMProjectionRepository_UpsertTenant_Call struct {
	*mock.Call
}

// UpsertTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - slug string
//   - name string
func (_e *MockIAMProjectionRepository_Expecter) UpsertTenant(ctx interface{}, tenantID interface{}, slug interface{}, name interface{}) *MockIAMProjectionRepository_UpsertTenant_Call {
	return &MockIAMProjectionRepository_UpsertTenant_Call{Call: _e.mock.On("UpsertTenant", ctx, tenantID, slug, name)}
}

func (_c *MockIAMProjectionRepository_UpsertTenant_Call) Run(run func(ctx context.Context, tenantID string, slug string, name string)) *MockIAMProjectionRepository_UpsertTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAMProjectionRepository_UpsertTenant_Call) Return(err error) *MockIAMProjectionRepository_UpsertTenant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAMProjectionRepository_UpsertTenant_Call) RunAndReturn(run func(ctx context.Context, tenantID string, slug string, name string) error) *MockIAMProjectionRepository_UpsertTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTenantMembership provides a mock function for the type MockIAMProjectionRepository
func (_mock *MockIAMProjectionRepository) UpsertTenantMembership(ctx context.Context, tenantID string, userID uint, roleName string, status string) error {
	ret := _mock.Called(ctx, tenantID, userID, roleName, status)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTenantMembership")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, userID, roleName, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAMProjectionRepository_UpsertTenantMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTenantMembership'
type MockIAMProjectionRepository_UpsertTenantMembership_Call struct {
	*mock.Call
}

// UpsertTenantMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID uint
//   - roleName string
//   - status string
func (_e *MockIAMProjectionRepository_Expecter) UpsertTenantMembership(ctx interface{}, tenantID interface{}, userID interface{}, roleName interface{}, status interface{}) *MockIAMProjectionRepository_UpsertTenantMembership_Call {
	return &MockIAMProjectionRepository_UpsertTenantMembership_Call{Call: _e.mock.On("UpsertTenantMembership", ctx, tenantID, userID, roleName, status)}
}

func (_c *MockIAMProjectionRepository_UpsertTenantMembership_Call) Run(run func(ctx context.Context, tenantID string, userID uint, roleName string, status string)) *MockIAMProjectionRepository_UpsertTenantMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIAMProjectionRepository_UpsertTenantMembership_Call) Return(err error) *MockIAMProjectionRepository_UpsertTenantMembership_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAMProjectionRepository_UpsertTenantMembership_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID uint, roleName string, status string) error) *MockIAMProjectionRepository_UpsertTenantMembership_Call {
	_c.Call.Return(run)
	return _c
}
