// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/auth/domain/entity"
	"github.com/tuannm99/podzone/pkg/collection"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Create(ctx context.Context, session entity.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session entity.Session
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session entity.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Session
		if args[1] != nil {
			arg1 = args[1].(entity.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(err error) *MockSessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session entity.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) GetByID(ctx context.Context, id string) (*entity.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSessionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSessionRepository_GetByID_Call {
	return &MockSessionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSessionRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_GetByID_Call) Return(session *entity.Session, err error) *MockSessionRepository_GetByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Session, error)) *MockSessionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) ListByUser(ctx context.Context, userID uint, query collection.Query) (collection.Page[entity.Session], error) {
	ret := _mock.Called(ctx, userID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 collection.Page[entity.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, collection.Query) (collection.Page[entity.Session], error)); ok {
		return returnFunc(ctx, userID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, collection.Query) collection.Page[entity.Session]); ok {
		r0 = returnFunc(ctx, userID, query)
	} else {
		r0 = ret.Get(0).(collection.Page[entity.Session])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, collection.Query) error); ok {
		r1 = returnFunc(ctx, userID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockSessionRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - query collection.Query
func (_e *MockSessionRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, query interface{}) *MockSessionRepository_ListByUser_Call {
	return &MockSessionRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, query)}
}

func (_c *MockSessionRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint, query collection.Query)) *MockSessionRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 collection.Query
		if args[2] != nil {
			arg2 = args[2].(collection.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_ListByUser_Call) Return(page collection.Page[entity.Session], err error) *MockSessionRepository_ListByUser_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockSessionRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, query collection.Query) (collection.Page[entity.Session], error)) *MockSessionRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Revoke(ctx context.Context, id string, revokedAt time.Time) error {
	ret := _mock.Called(ctx, id, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, revokedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - revokedAt time.Time
func (_e *MockSessionRepository_Expecter) Revoke(ctx interface{}, id interface{}, revokedAt interface{}) *MockSessionRepository_Revoke_Call {
	return &MockSessionRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, revokedAt)}
}

func (_c *MockSessionRepository_Revoke_Call) Run(run func(ctx context.Context, id string, revokedAt time.Time)) *MockSessionRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Revoke_Call) Return(err error) *MockSessionRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id string, revokedAt time.Time) error) *MockSessionRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActiveTenant provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateActiveTenant(ctx context.Context, id string, tenantID string, updatedAt time.Time) error {
	ret := _mock.Called(ctx, id, tenantID, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActiveTenant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, tenantID, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateActiveTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActiveTenant'
type MockSessionRepository_UpdateActiveTenant_Call struct {
	*mock.Call
}

// UpdateActiveTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tenantID string
//   - updatedAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateActiveTenant(ctx interface{}, id interface{}, tenantID interface{}, updatedAt interface{}) *MockSessionRepository_UpdateActiveTenant_Call {
	return &MockSessionRepository_UpdateActiveTenant_Call{Call: _e.mock.On("UpdateActiveTenant", ctx, id, tenantID, updatedAt)}
}

func (_c *MockSessionRepository_UpdateActiveTenant_Call) Run(run func(ctx context.Context, id string, tenantID string, updatedAt time.Time)) *MockSessionRepository_UpdateActiveTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateActiveTenant_Call) Return(err error) *MockSessionRepository_UpdateActiveTenant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateActiveTenant_Call) RunAndReturn(run func(ctx context.Context, id string, tenantID string, updatedAt time.Time) error) *MockSessionRepository_UpdateActiveTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAssumedRole provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateAssumedRole(ctx context.Context, session entity.Session, updatedAt time.Time) error {
	ret := _mock.Called(ctx, session, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAssumedRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Session, time.Time) error); ok {
		r0 = returnFunc(ctx, session, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateAssumedRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAssumedRole'
type MockSessionRepository_UpdateAssumedRole_Call struct {
	*mock.Call
}

// UpdateAssumedRole is a helper method to define mock.On call
//   - ctx context.Context
//   - session entity.Session
//   - updatedAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateAssumedRole(ctx interface{}, session interface{}, updatedAt interface{}) *MockSessionRepository_UpdateAssumedRole_Call {
	return &MockSessionRepository_UpdateAssumedRole_Call{Call: _e.mock.On("UpdateAssumedRole", ctx, session, updatedAt)}
}

func (_c *MockSessionRepository_UpdateAssumedRole_Call) Run(run func(ctx context.Context, session entity.Session, updatedAt time.Time)) *MockSessionRepository_UpdateAssumedRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Session
		if args[1] != nil {
			arg1 = args[1].(entity.Session)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateAssumedRole_Call) Return(err error) *MockSessionRepository_UpdateAssumedRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateAssumedRole_Call) RunAndReturn(run func(ctx context.Context, session entity.Session, updatedAt time.Time) error) *MockSessionRepository_UpdateAssumedRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionPolicy provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateSessionPolicy(ctx context.Context, id string, statements []entity.SessionPolicyStatement, updatedAt time.Time) error {
	ret := _mock.Called(ctx, id, statements, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []entity.SessionPolicyStatement, time.Time) error); ok {
		r0 = returnFunc(ctx, id, statements, updatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateSessionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionPolicy'
type MockSessionRepository_UpdateSessionPolicy_Call struct {
	*mock.Call
}

// UpdateSessionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - statements []entity.SessionPolicyStatement
//   - updatedAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateSessionPolicy(ctx interface{}, id interface{}, statements interface{}, updatedAt interface{}) *MockSessionRepository_UpdateSessionPolicy_Call {
	return &MockSessionRepository_UpdateSessionPolicy_Call{Call: _e.mock.On("UpdateSessionPolicy", ctx, id, statements, updatedAt)}
}

func (_c *MockSessionRepository_UpdateSessionPolicy_Call) Run(run func(ctx context.Context, id string, statements []entity.SessionPolicyStatement, updatedAt time.Time)) *MockSessionRepository_UpdateSessionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entity.SessionPolicyStatement
		if args[2] != nil {
			arg2 = args[2].([]entity.SessionPolicyStatement)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateSessionPolicy_Call) Return(err error) *MockSessionRepository_UpdateSessionPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateSessionPolicy_Call) RunAndReturn(run func(ctx context.Context, id string, statements []entity.SessionPolicyStatement, updatedAt time.Time) error) *MockSessionRepository_UpdateSessionPolicy_Call {
	_c.Call.Return(run)
	return _c
}
