// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/backoffice/domain/routing/entity"
)

// NewMockOrderRoutingRepository creates a new instance of MockOrderRoutingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRoutingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRoutingRepository {
	mock := &MockOrderRoutingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRoutingRepository is an autogenerated mock type for the OrderRoutingRepository type
type MockOrderRoutingRepository struct {
	mock.Mock
}

type MockOrderRoutingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRoutingRepository) EXPECT() *MockOrderRoutingRepository_Expecter {
	return &MockOrderRoutingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRoutingRepository
func (_mock *MockOrderRoutingRepository) Create(ctx context.Context, order entity.RoutedOrder) (*entity.RoutedOrder, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrder) (*entity.RoutedOrder, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrder) *entity.RoutedOrder); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.RoutedOrder) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRoutingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order entity.RoutedOrder
func (_e *MockOrderRoutingRepository_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRoutingRepository_Create_Call {
	return &MockOrderRoutingRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRoutingRepository_Create_Call) Run(run func(ctx context.Context, order entity.RoutedOrder)) *MockOrderRoutingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.RoutedOrder
		if args[1] != nil {
			arg1 = args[1].(entity.RoutedOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingRepository_Create_Call) Return(routedOrder *entity.RoutedOrder, err error) *MockOrderRoutingRepository_Create_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order entity.RoutedOrder) (*entity.RoutedOrder, error)) *MockOrderRoutingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRoutingRepository
func (_mock *MockOrderRoutingRepository) GetByID(ctx context.Context, id string) (*entity.RoutedOrder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RoutedOrder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RoutedOrder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRoutingRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRoutingRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrderRoutingRepository_GetByID_Call {
	return &MockOrderRoutingRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRoutingRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockOrderRoutingRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingRepository_GetByID_Call) Return(routedOrder *entity.RoutedOrder, err error) *MockOrderRoutingRepository_GetByID_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.RoutedOrder, error)) *MockOrderRoutingRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrderRoutingRepository
func (_mock *MockOrderRoutingRepository) List(ctx context.Context) ([]entity.RoutedOrder, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.RoutedOrder, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.RoutedOrder); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRoutingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderRoutingRepository_Expecter) List(ctx interface{}) *MockOrderRoutingRepository_List_Call {
	return &MockOrderRoutingRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockOrderRoutingRepository_List_Call) Run(run func(ctx context.Context)) *MockOrderRoutingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderRoutingRepository_List_Call) Return(routedOrders []entity.RoutedOrder, err error) *MockOrderRoutingRepository_List_Call {
	_c.Call.Return(routedOrders, err)
	return _c
}

func (_c *MockOrderRoutingRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]entity.RoutedOrder, error)) *MockOrderRoutingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivityFeed provides a mock function for the type MockOrderRoutingRepository
func (_mock *MockOrderRoutingRepository) ListActivityFeed(ctx context.Context, query entity.RoutedOrderActivityFeedQuery) (*entity.RoutedOrderActivityFeedPage, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListActivityFeed")
	}

	var r0 *entity.RoutedOrderActivityFeedPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrderActivityFeedQuery) (*entity.RoutedOrderActivityFeedPage, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrderActivityFeedQuery) *entity.RoutedOrderActivityFeedPage); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RoutedOrderActivityFeedPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.RoutedOrderActivityFeedQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingRepository_ListActivityFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivityFeed'
type MockOrderRoutingRepository_ListActivityFeed_Call struct {
	*mock.Call
}

// ListActivityFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - query entity.RoutedOrderActivityFeedQuery
func (_e *MockOrderRoutingRepository_Expecter) ListActivityFeed(ctx interface{}, query interface{}) *MockOrderRoutingRepository_ListActivityFeed_Call {
	return &MockOrderRoutingRepository_ListActivityFeed_Call{Call: _e.mock.On("ListActivityFeed", ctx, query)}
}

func (_c *MockOrderRoutingRepository_ListActivityFeed_Call) Run(run func(ctx context.Context, query entity.RoutedOrderActivityFeedQuery)) *MockOrderRoutingRepository_ListActivityFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.RoutedOrderActivityFeedQuery
		if args[1] != nil {
			arg1 = args[1].(entity.RoutedOrderActivityFeedQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingRepository_ListActivityFeed_Call) Return(routedOrderActivityFeedPage *entity.RoutedOrderActivityFeedPage, err error) *MockOrderRoutingRepository_ListActivityFeed_Call {
	_c.Call.Return(routedOrderActivityFeedPage, err)
	return _c
}

func (_c *MockOrderRoutingRepository_ListActivityFeed_Call) RunAndReturn(run func(ctx context.Context, query entity.RoutedOrderActivityFeedQuery) (*entity.RoutedOrderActivityFeedPage, error)) *MockOrderRoutingRepository_ListActivityFeed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrderRoutingRepository
func (_mock *MockOrderRoutingRepository) Update(ctx context.Context, order entity.RoutedOrder) (*entity.RoutedOrder, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.RoutedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrder) (*entity.RoutedOrder, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.RoutedOrder) *entity.RoutedOrder); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RoutedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.RoutedOrder) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRoutingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRoutingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order entity.RoutedOrder
func (_e *MockOrderRoutingRepository_Expecter) Update(ctx interface{}, order interface{}) *MockOrderRoutingRepository_Update_Call {
	return &MockOrderRoutingRepository_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockOrderRoutingRepository_Update_Call) Run(run func(ctx context.Context, order entity.RoutedOrder)) *MockOrderRoutingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.RoutedOrder
		if args[1] != nil {
			arg1 = args[1].(entity.RoutedOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRoutingRepository_Update_Call) Return(routedOrder *entity.RoutedOrder, err error) *MockOrderRoutingRepository_Update_Call {
	_c.Call.Return(routedOrder, err)
	return _c
}

func (_c *MockOrderRoutingRepository_Update_Call) RunAndReturn(run func(ctx context.Context, order entity.RoutedOrder) (*entity.RoutedOrder, error)) *MockOrderRoutingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
