logger:
  provider: zap
  level: debug
  env: dev
  app_name: podzone_onboarding

consul_kv:
  address: 'http://consul:8500'
  token: ''
  tls:
    insecure_skip_verify: true

mongo:
  onboarding:
    uri: mongodb://podzone:podzone123@mongo:27017
    database: onboarding
    ping_timeout: 3s
    connect_timeout: 5s

onboarding:
  store_provisioning:
    enabled: true
    auto_approve: true
    interval: 5s
    runtime: local_docker
    cluster_name: pg-default
    mode: schema
    db_name: postgres
    schema_prefix: t_
    docker_network: docker_default
    kubernetes_namespace: default
    terraform_workspace: default

http:
  address: ':8800'
  trusted_proxies: []

pprof:
  enable: false
  addr: '127.0.0.1:6060'
