// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/onboarding/domain/infrasmanager/entity"
)

// NewMockPlacementRouteWriter creates a new instance of MockPlacementRouteWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlacementRouteWriter(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPlacementRouteWriter {
	mock := &MockPlacementRouteWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlacementRouteWriter is an autogenerated mock type for the PlacementRouteWriter type
type MockPlacementRouteWriter struct {
	mock.Mock
}

type MockPlacementRouteWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlacementRouteWriter) EXPECT() *MockPlacementRouteWriter_Expecter {
	return &MockPlacementRouteWriter_Expecter{mock: &_m.Mock}
}

// PublishPlacementRoute provides a mock function for the type MockPlacementRouteWriter
func (_mock *MockPlacementRouteWriter) PublishPlacementRoute(ctx context.Context, tenantID string, allocation entity.PlacementAllocation) error {
	ret := _mock.Called(ctx, tenantID, allocation)

	if len(ret) == 0 {
		panic("no return value specified for PublishPlacementRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.PlacementAllocation) error); ok {
		r0 = returnFunc(ctx, tenantID, allocation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlacementRouteWriter_PublishPlacementRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishPlacementRoute'
type MockPlacementRouteWriter_PublishPlacementRoute_Call struct {
	*mock.Call
}

// PublishPlacementRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - allocation entity.PlacementAllocation
func (_e *MockPlacementRouteWriter_Expecter) PublishPlacementRoute(ctx interface{}, tenantID interface{}, allocation interface{}) *MockPlacementRouteWriter_PublishPlacementRoute_Call {
	return &MockPlacementRouteWriter_PublishPlacementRoute_Call{Call: _e.mock.On("PublishPlacementRoute", ctx, tenantID, allocation)}
}

func (_c *MockPlacementRouteWriter_PublishPlacementRoute_Call) Run(run func(ctx context.Context, tenantID string, allocation entity.PlacementAllocation)) *MockPlacementRouteWriter_PublishPlacementRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.PlacementAllocation
		if args[2] != nil {
			arg2 = args[2].(entity.PlacementAllocation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlacementRouteWriter_PublishPlacementRoute_Call) Return(err error) *MockPlacementRouteWriter_PublishPlacementRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlacementRouteWriter_PublishPlacementRoute_Call) RunAndReturn(run func(ctx context.Context, tenantID string, allocation entity.PlacementAllocation) error) *MockPlacementRouteWriter_PublishPlacementRoute_Call {
	_c.Call.Return(run)
	return _c
}
