// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/onboarding/domain/infrasmanager/entity"
)

// NewMockResourceHealthChecker creates a new instance of MockResourceHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceHealthChecker {
	mock := &MockResourceHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceHealthChecker is an autogenerated mock type for the ResourceHealthChecker type
type MockResourceHealthChecker struct {
	mock.Mock
}

type MockResourceHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceHealthChecker) EXPECT() *MockResourceHealthChecker_Expecter {
	return &MockResourceHealthChecker_Expecter{mock: &_m.Mock}
}

// CheckDatabaseClusterHealth provides a mock function for the type MockResourceHealthChecker
func (_mock *MockResourceHealthChecker) CheckDatabaseClusterHealth(ctx context.Context, cluster entity.DatabaseCluster) (entity.DatabaseClusterHealth, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for CheckDatabaseClusterHealth")
	}

	var r0 entity.DatabaseClusterHealth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.DatabaseCluster) (entity.DatabaseClusterHealth, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.DatabaseCluster) entity.DatabaseClusterHealth); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		r0 = ret.Get(0).(entity.DatabaseClusterHealth)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.DatabaseCluster) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceHealthChecker_CheckDatabaseClusterHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDatabaseClusterHealth'
type MockResourceHealthChecker_CheckDatabaseClusterHealth_Call struct {
	*mock.Call
}

// CheckDatabaseClusterHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster entity.DatabaseCluster
func (_e *MockResourceHealthChecker_Expecter) CheckDatabaseClusterHealth(ctx interface{}, cluster interface{}) *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call {
	return &MockResourceHealthChecker_CheckDatabaseClusterHealth_Call{Call: _e.mock.On("CheckDatabaseClusterHealth", ctx, cluster)}
}

func (_c *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call) Run(run func(ctx context.Context, cluster entity.DatabaseCluster)) *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.DatabaseCluster
		if args[1] != nil {
			arg1 = args[1].(entity.DatabaseCluster)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call) Return(databaseClusterHealth entity.DatabaseClusterHealth, err error) *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call {
	_c.Call.Return(databaseClusterHealth, err)
	return _c
}

func (_c *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call) RunAndReturn(run func(ctx context.Context, cluster entity.DatabaseCluster) (entity.DatabaseClusterHealth, error)) *MockResourceHealthChecker_CheckDatabaseClusterHealth_Call {
	_c.Call.Return(run)
	return _c
}
