// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/onboarding/domain/infrasmanager/entity"
)

// NewMockPlacementRepository creates a new instance of MockPlacementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlacementRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPlacementRepository {
	mock := &MockPlacementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlacementRepository is an autogenerated mock type for the PlacementRepository type
type MockPlacementRepository struct {
	mock.Mock
}

type MockPlacementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlacementRepository) EXPECT() *MockPlacementRepository_Expecter {
	return &MockPlacementRepository_Expecter{mock: &_m.Mock}
}

// GetTenantPlacementAllocation provides a mock function for the type MockPlacementRepository
func (_mock *MockPlacementRepository) GetTenantPlacementAllocation(ctx context.Context, tenantID string) (*entity.PlacementAllocation, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantPlacementAllocation")
	}

	var r0 *entity.PlacementAllocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.PlacementAllocation, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.PlacementAllocation); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlacementAllocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlacementRepository_GetTenantPlacementAllocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantPlacementAllocation'
type MockPlacementRepository_GetTenantPlacementAllocation_Call struct {
	*mock.Call
}

// GetTenantPlacementAllocation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockPlacementRepository_Expecter) GetTenantPlacementAllocation(ctx interface{}, tenantID interface{}) *MockPlacementRepository_GetTenantPlacementAllocation_Call {
	return &MockPlacementRepository_GetTenantPlacementAllocation_Call{Call: _e.mock.On("GetTenantPlacementAllocation", ctx, tenantID)}
}

func (_c *MockPlacementRepository_GetTenantPlacementAllocation_Call) Run(run func(ctx context.Context, tenantID string)) *MockPlacementRepository_GetTenantPlacementAllocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlacementRepository_GetTenantPlacementAllocation_Call) Return(placementAllocation *entity.PlacementAllocation, err error) *MockPlacementRepository_GetTenantPlacementAllocation_Call {
	_c.Call.Return(placementAllocation, err)
	return _c
}

func (_c *MockPlacementRepository_GetTenantPlacementAllocation_Call) RunAndReturn(run func(ctx context.Context, tenantID string) (*entity.PlacementAllocation, error)) *MockPlacementRepository_GetTenantPlacementAllocation_Call {
	_c.Call.Return(run)
	return _c
}

// SavePlacementAllocation provides a mock function for the type MockPlacementRepository
func (_mock *MockPlacementRepository) SavePlacementAllocation(ctx context.Context, allocation entity.PlacementAllocation) error {
	ret := _mock.Called(ctx, allocation)

	if len(ret) == 0 {
		panic("no return value specified for SavePlacementAllocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.PlacementAllocation) error); ok {
		r0 = returnFunc(ctx, allocation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlacementRepository_SavePlacementAllocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePlacementAllocation'
type MockPlacementRepository_SavePlacementAllocation_Call struct {
	*mock.Call
}

// SavePlacementAllocation is a helper method to define mock.On call
//   - ctx context.Context
//   - allocation entity.PlacementAllocation
func (_e *MockPlacementRepository_Expecter) SavePlacementAllocation(ctx interface{}, allocation interface{}) *MockPlacementRepository_SavePlacementAllocation_Call {
	return &MockPlacementRepository_SavePlacementAllocation_Call{Call: _e.mock.On("SavePlacementAllocation", ctx, allocation)}
}

func (_c *MockPlacementRepository_SavePlacementAllocation_Call) Run(run func(ctx context.Context, allocation entity.PlacementAllocation)) *MockPlacementRepository_SavePlacementAllocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.PlacementAllocation
		if args[1] != nil {
			arg1 = args[1].(entity.PlacementAllocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlacementRepository_SavePlacementAllocation_Call) Return(err error) *MockPlacementRepository_SavePlacementAllocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlacementRepository_SavePlacementAllocation_Call) RunAndReturn(run func(ctx context.Context, allocation entity.PlacementAllocation) error) *MockPlacementRepository_SavePlacementAllocation_Call {
	_c.Call.Return(run)
	return _c
}
