// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/domain/entity"
	"github.com/tuannm99/podzone/pkg/collection"
)

// NewMockInviteQueryRepository creates a new instance of MockInviteQueryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteQueryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteQueryRepository {
	mock := &MockInviteQueryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInviteQueryRepository is an autogenerated mock type for the InviteQueryRepository type
type MockInviteQueryRepository struct {
	mock.Mock
}

type MockInviteQueryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteQueryRepository) EXPECT() *MockInviteQueryRepository_Expecter {
	return &MockInviteQueryRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockInviteQueryRepository
func (_mock *MockInviteQueryRepository) GetByID(ctx context.Context, inviteID string) (*entity.TenantInvite, error) {
	ret := _mock.Called(ctx, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TenantInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.TenantInvite, error)); ok {
		return returnFunc(ctx, inviteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.TenantInvite); ok {
		r0 = returnFunc(ctx, inviteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantInvite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, inviteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInviteQueryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockInviteQueryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteID string
func (_e *MockInviteQueryRepository_Expecter) GetByID(ctx interface{}, inviteID interface{}) *MockInviteQueryRepository_GetByID_Call {
	return &MockInviteQueryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, inviteID)}
}

func (_c *MockInviteQueryRepository_GetByID_Call) Run(run func(ctx context.Context, inviteID string)) *MockInviteQueryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInviteQueryRepository_GetByID_Call) Return(tenantInvite *entity.TenantInvite, err error) *MockInviteQueryRepository_GetByID_Call {
	_c.Call.Return(tenantInvite, err)
	return _c
}

func (_c *MockInviteQueryRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, inviteID string) (*entity.TenantInvite, error)) *MockInviteQueryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockInviteQueryRepository
func (_mock *MockInviteQueryRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*entity.TenantInvite, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *entity.TenantInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.TenantInvite, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.TenantInvite); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantInvite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInviteQueryRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockInviteQueryRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockInviteQueryRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *MockInviteQueryRepository_GetByTokenHash_Call {
	return &MockInviteQueryRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockInviteQueryRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockInviteQueryRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInviteQueryRepository_GetByTokenHash_Call) Return(tenantInvite *entity.TenantInvite, err error) *MockInviteQueryRepository_GetByTokenHash_Call {
	_c.Call.Return(tenantInvite, err)
	return _c
}

func (_c *MockInviteQueryRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*entity.TenantInvite, error)) *MockInviteQueryRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListPageByTenant provides a mock function for the type MockInviteQueryRepository
func (_mock *MockInviteQueryRepository) ListPageByTenant(ctx context.Context, tenantID string, query collection.Query) (collection.Page[entity.TenantInvite], error) {
	ret := _mock.Called(ctx, tenantID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListPageByTenant")
	}

	var r0 collection.Page[entity.TenantInvite]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, collection.Query) (collection.Page[entity.TenantInvite], error)); ok {
		return returnFunc(ctx, tenantID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, collection.Query) collection.Page[entity.TenantInvite]); ok {
		r0 = returnFunc(ctx, tenantID, query)
	} else {
		r0 = ret.Get(0).(collection.Page[entity.TenantInvite])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, collection.Query) error); ok {
		r1 = returnFunc(ctx, tenantID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInviteQueryRepository_ListPageByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPageByTenant'
type MockInviteQueryRepository_ListPageByTenant_Call struct {
	*mock.Call
}

// ListPageByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - query collection.Query
func (_e *MockInviteQueryRepository_Expecter) ListPageByTenant(ctx interface{}, tenantID interface{}, query interface{}) *MockInviteQueryRepository_ListPageByTenant_Call {
	return &MockInviteQueryRepository_ListPageByTenant_Call{Call: _e.mock.On("ListPageByTenant", ctx, tenantID, query)}
}

func (_c *MockInviteQueryRepository_ListPageByTenant_Call) Run(run func(ctx context.Context, tenantID string, query collection.Query)) *MockInviteQueryRepository_ListPageByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 collection.Query
		if args[2] != nil {
			arg2 = args[2].(collection.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInviteQueryRepository_ListPageByTenant_Call) Return(page collection.Page[entity.TenantInvite], err error) *MockInviteQueryRepository_ListPageByTenant_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockInviteQueryRepository_ListPageByTenant_Call) RunAndReturn(run func(ctx context.Context, tenantID string, query collection.Query) (collection.Page[entity.TenantInvite], error)) *MockInviteQueryRepository_ListPageByTenant_Call {
	_c.Call.Return(run)
	return _c
}
