// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/iam/domain/entity"
	"github.com/tuannm99/podzone/pkg/collection"
)

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// DeletePermissionBoundary provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) DeletePermissionBoundary(ctx context.Context, roleID uint64) error {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermissionBoundary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_DeletePermissionBoundary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermissionBoundary'
type MockRoleRepository_DeletePermissionBoundary_Call struct {
	*mock.Call
}

// DeletePermissionBoundary is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockRoleRepository_Expecter) DeletePermissionBoundary(ctx interface{}, roleID interface{}) *MockRoleRepository_DeletePermissionBoundary_Call {
	return &MockRoleRepository_DeletePermissionBoundary_Call{Call: _e.mock.On("DeletePermissionBoundary", ctx, roleID)}
}

func (_c *MockRoleRepository_DeletePermissionBoundary_Call) Run(run func(ctx context.Context, roleID uint64)) *MockRoleRepository_DeletePermissionBoundary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_DeletePermissionBoundary_Call) Return(err error) *MockRoleRepository_DeletePermissionBoundary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_DeletePermissionBoundary_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) error) *MockRoleRepository_DeletePermissionBoundary_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrustPolicy provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) DeleteTrustPolicy(ctx context.Context, roleID uint64) error {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrustPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_DeleteTrustPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrustPolicy'
type MockRoleRepository_DeleteTrustPolicy_Call struct {
	*mock.Call
}

// DeleteTrustPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockRoleRepository_Expecter) DeleteTrustPolicy(ctx interface{}, roleID interface{}) *MockRoleRepository_DeleteTrustPolicy_Call {
	return &MockRoleRepository_DeleteTrustPolicy_Call{Call: _e.mock.On("DeleteTrustPolicy", ctx, roleID)}
}

func (_c *MockRoleRepository_DeleteTrustPolicy_Call) Run(run func(ctx context.Context, roleID uint64)) *MockRoleRepository_DeleteTrustPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_DeleteTrustPolicy_Call) Return(err error) *MockRoleRepository_DeleteTrustPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_DeleteTrustPolicy_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) error) *MockRoleRepository_DeleteTrustPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) GetByName(ctx context.Context, name string) (*entity.Role, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRoleRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockRoleRepository_GetByName_Call {
	return &MockRoleRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockRoleRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_GetByName_Call) Return(role *entity.Role, err error) *MockRoleRepository_GetByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Role, error)) *MockRoleRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionBoundary provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) GetPermissionBoundary(ctx context.Context, roleID uint64) (*entity.RolePermissionBoundary, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionBoundary")
	}

	var r0 *entity.RolePermissionBoundary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*entity.RolePermissionBoundary, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *entity.RolePermissionBoundary); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RolePermissionBoundary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_GetPermissionBoundary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionBoundary'
type MockRoleRepository_GetPermissionBoundary_Call struct {
	*mock.Call
}

// GetPermissionBoundary is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockRoleRepository_Expecter) GetPermissionBoundary(ctx interface{}, roleID interface{}) *MockRoleRepository_GetPermissionBoundary_Call {
	return &MockRoleRepository_GetPermissionBoundary_Call{Call: _e.mock.On("GetPermissionBoundary", ctx, roleID)}
}

func (_c *MockRoleRepository_GetPermissionBoundary_Call) Run(run func(ctx context.Context, roleID uint64)) *MockRoleRepository_GetPermissionBoundary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_GetPermissionBoundary_Call) Return(rolePermissionBoundary *entity.RolePermissionBoundary, err error) *MockRoleRepository_GetPermissionBoundary_Call {
	_c.Call.Return(rolePermissionBoundary, err)
	return _c
}

func (_c *MockRoleRepository_GetPermissionBoundary_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) (*entity.RolePermissionBoundary, error)) *MockRoleRepository_GetPermissionBoundary_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionBoundaryStatements provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) GetPermissionBoundaryStatements(ctx context.Context, roleID uint64) ([]entity.PolicyStatement, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionBoundaryStatements")
	}

	var r0 []entity.PolicyStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]entity.PolicyStatement, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []entity.PolicyStatement); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PolicyStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_GetPermissionBoundaryStatements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionBoundaryStatements'
type MockRoleRepository_GetPermissionBoundaryStatements_Call struct {
	*mock.Call
}

// GetPermissionBoundaryStatements is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockRoleRepository_Expecter) GetPermissionBoundaryStatements(ctx interface{}, roleID interface{}) *MockRoleRepository_GetPermissionBoundaryStatements_Call {
	return &MockRoleRepository_GetPermissionBoundaryStatements_Call{Call: _e.mock.On("GetPermissionBoundaryStatements", ctx, roleID)}
}

func (_c *MockRoleRepository_GetPermissionBoundaryStatements_Call) Run(run func(ctx context.Context, roleID uint64)) *MockRoleRepository_GetPermissionBoundaryStatements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_GetPermissionBoundaryStatements_Call) Return(policyStatements []entity.PolicyStatement, err error) *MockRoleRepository_GetPermissionBoundaryStatements_Call {
	_c.Call.Return(policyStatements, err)
	return _c
}

func (_c *MockRoleRepository_GetPermissionBoundaryStatements_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) ([]entity.PolicyStatement, error)) *MockRoleRepository_GetPermissionBoundaryStatements_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrustPolicy provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) GetTrustPolicy(ctx context.Context, roleID uint64) ([]entity.RoleTrustStatement, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrustPolicy")
	}

	var r0 []entity.RoleTrustStatement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]entity.RoleTrustStatement, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []entity.RoleTrustStatement); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RoleTrustStatement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_GetTrustPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrustPolicy'
type MockRoleRepository_GetTrustPolicy_Call struct {
	*mock.Call
}

// GetTrustPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
func (_e *MockRoleRepository_Expecter) GetTrustPolicy(ctx interface{}, roleID interface{}) *MockRoleRepository_GetTrustPolicy_Call {
	return &MockRoleRepository_GetTrustPolicy_Call{Call: _e.mock.On("GetTrustPolicy", ctx, roleID)}
}

func (_c *MockRoleRepository_GetTrustPolicy_Call) Run(run func(ctx context.Context, roleID uint64)) *MockRoleRepository_GetTrustPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_GetTrustPolicy_Call) Return(roleTrustStatements []entity.RoleTrustStatement, err error) *MockRoleRepository_GetTrustPolicy_Call {
	_c.Call.Return(roleTrustStatements, err)
	return _c
}

func (_c *MockRoleRepository_GetTrustPolicy_Call) RunAndReturn(run func(ctx context.Context, roleID uint64) ([]entity.RoleTrustStatement, error)) *MockRoleRepository_GetTrustPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) ListPermissions(ctx context.Context, query collection.Query) (collection.Page[entity.Permission], error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 collection.Page[entity.Permission]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, collection.Query) (collection.Page[entity.Permission], error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, collection.Query) collection.Page[entity.Permission]); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(collection.Page[entity.Permission])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, collection.Query) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockRoleRepository_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - query collection.Query
func (_e *MockRoleRepository_Expecter) ListPermissions(ctx interface{}, query interface{}) *MockRoleRepository_ListPermissions_Call {
	return &MockRoleRepository_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx, query)}
}

func (_c *MockRoleRepository_ListPermissions_Call) Run(run func(ctx context.Context, query collection.Query)) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 collection.Query
		if args[1] != nil {
			arg1 = args[1].(collection.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_ListPermissions_Call) Return(page collection.Page[entity.Permission], err error) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockRoleRepository_ListPermissions_Call) RunAndReturn(run func(ctx context.Context, query collection.Query) (collection.Page[entity.Permission], error)) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// PutPermissionBoundary provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) PutPermissionBoundary(ctx context.Context, roleID uint64, policyID uint64) error {
	ret := _mock.Called(ctx, roleID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for PutPermissionBoundary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = returnFunc(ctx, roleID, policyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_PutPermissionBoundary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPermissionBoundary'
type MockRoleRepository_PutPermissionBoundary_Call struct {
	*mock.Call
}

// PutPermissionBoundary is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
//   - policyID uint64
func (_e *MockRoleRepository_Expecter) PutPermissionBoundary(ctx interface{}, roleID interface{}, policyID interface{}) *MockRoleRepository_PutPermissionBoundary_Call {
	return &MockRoleRepository_PutPermissionBoundary_Call{Call: _e.mock.On("PutPermissionBoundary", ctx, roleID, policyID)}
}

func (_c *MockRoleRepository_PutPermissionBoundary_Call) Run(run func(ctx context.Context, roleID uint64, policyID uint64)) *MockRoleRepository_PutPermissionBoundary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleRepository_PutPermissionBoundary_Call) Return(err error) *MockRoleRepository_PutPermissionBoundary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_PutPermissionBoundary_Call) RunAndReturn(run func(ctx context.Context, roleID uint64, policyID uint64) error) *MockRoleRepository_PutPermissionBoundary_Call {
	_c.Call.Return(run)
	return _c
}

// PutTrustPolicy provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) PutTrustPolicy(ctx context.Context, roleID uint64, statements []entity.RoleTrustStatement) error {
	ret := _mock.Called(ctx, roleID, statements)

	if len(ret) == 0 {
		panic("no return value specified for PutTrustPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []entity.RoleTrustStatement) error); ok {
		r0 = returnFunc(ctx, roleID, statements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_PutTrustPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTrustPolicy'
type MockRoleRepository_PutTrustPolicy_Call struct {
	*mock.Call
}

// PutTrustPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
//   - statements []entity.RoleTrustStatement
func (_e *MockRoleRepository_Expecter) PutTrustPolicy(ctx interface{}, roleID interface{}, statements interface{}) *MockRoleRepository_PutTrustPolicy_Call {
	return &MockRoleRepository_PutTrustPolicy_Call{Call: _e.mock.On("PutTrustPolicy", ctx, roleID, statements)}
}

func (_c *MockRoleRepository_PutTrustPolicy_Call) Run(run func(ctx context.Context, roleID uint64, statements []entity.RoleTrustStatement)) *MockRoleRepository_PutTrustPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []entity.RoleTrustStatement
		if args[2] != nil {
			arg2 = args[2].([]entity.RoleTrustStatement)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleRepository_PutTrustPolicy_Call) Return(err error) *MockRoleRepository_PutTrustPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_PutTrustPolicy_Call) RunAndReturn(run func(ctx context.Context, roleID uint64, statements []entity.RoleTrustStatement) error) *MockRoleRepository_PutTrustPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RoleHasPermission provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) RoleHasPermission(ctx context.Context, roleID uint64, permission string) (bool, error) {
	ret := _mock.Called(ctx, roleID, permission)

	if len(ret) == 0 {
		panic("no return value specified for RoleHasPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) (bool, error)); ok {
		return returnFunc(ctx, roleID, permission)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string) bool); ok {
		r0 = returnFunc(ctx, roleID, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = returnFunc(ctx, roleID, permission)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_RoleHasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleHasPermission'
type MockRoleRepository_RoleHasPermission_Call struct {
	*mock.Call
}

// RoleHasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint64
//   - permission string
func (_e *MockRoleRepository_Expecter) RoleHasPermission(ctx interface{}, roleID interface{}, permission interface{}) *MockRoleRepository_RoleHasPermission_Call {
	return &MockRoleRepository_RoleHasPermission_Call{Call: _e.mock.On("RoleHasPermission", ctx, roleID, permission)}
}

func (_c *MockRoleRepository_RoleHasPermission_Call) Run(run func(ctx context.Context, roleID uint64, permission string)) *MockRoleRepository_RoleHasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleRepository_RoleHasPermission_Call) Return(b bool, err error) *MockRoleRepository_RoleHasPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRoleRepository_RoleHasPermission_Call) RunAndReturn(run func(ctx context.Context, roleID uint64, permission string) (bool, error)) *MockRoleRepository_RoleHasPermission_Call {
	_c.Call.Return(run)
	return _c
}
