apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-service
  labels:
    app: backoffice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-service
  template:
    metadata:
      labels:
        app: backoffice-service
    spec:
      containers:
        - name: backoffice-service
          image: tuannm99/podzone-backoffice:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: GIN_MODE
              value: 'release'
            - name: PORT
              value: '8000'
            - name: GRAPHQL_QUERY_URI
              value: '/api/backoffice/query'

          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
spec:
  selector:
    app: backoffice-service
  ports:
    - port: 8000
      name: http
      targetPort: 8000
