apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-service
  labels:
    app: onboarding-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-service
  template:
    metadata:
      labels:
        app: onboarding-service
    spec:
      containers:
        - name: onboarding-service
          image: localhost:5000/podzone-onboarding:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: APP_ENV
            - name: DEFAULT_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: DEFAULT_LOG_LEVEL
            - name: OAUTH_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: OAUTH_REDIRECT_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: JWT_SECRET

            - name: GIN_MODE
              value: 'release'
            - name: HTTP_PORT
              value: '8080'
            - name: REDIS_ADDR
              value: 'redis://redis:6379/0'

          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
spec:
  selector:
    app: onboarding-service
  ports:
    - port: 8080
      name: http
      targetPort: 8080
