apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-service
  labels:
    app: storefront-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront-service
  template:
    metadata:
      labels:
        app: storefront-service
    spec:
      containers:
        - name: storefront-service
          image: tuannm99/podzone-storefront:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GIN_MODE
              value: 'release'
            - name: PORT
              value: '3000'

          resources:
            limits:
              cpu: '20m'
              memory: '50Mi'
            requests:
              cpu: '50m'
              memory: '128Mi'
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: storefront-service
spec:
  selector:
    app: storefront-service
  ports:
    - port: 3000
      name: http
      targetPort: 3000
