apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-admin
  template:
    metadata:
      labels:
        app: ui-admin
    spec:
      containers:
        - name: ui-admin
          image: tuannm99/podzone-ui-admin:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '256Mi'
              cpu: '250m'

---
apiVersion: v1
kind: Service
metadata:
  name: ui-admin
spec:
  selector:
    app: ui-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-admin
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: 'letsencrypt-dev'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin-ui.tuannm.uk
      secretName: gateway-tls
  rules:
    - host: admin-ui.tuannm.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-admin
                port:
                  number: 80
