// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/podzone/internal/backoffice/domain/entity"
	"github.com/tuannm99/podzone/internal/backoffice/infrastructure/model"
)

// NewMockStoreRepository creates a new instance of MockStoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreRepository {
	mock := &MockStoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreRepository is an autogenerated mock type for the StoreRepository type
type MockStoreRepository struct {
	mock.Mock
}

type MockStoreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreRepository) EXPECT() *MockStoreRepository_Expecter {
	return &MockStoreRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStoreRepository
func (_mock *MockStoreRepository) Create(ctx context.Context, s *model.Store) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Store) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStoreRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *model.Store
func (_e *MockStoreRepository_Expecter) Create(ctx interface{}, s interface{}) *MockStoreRepository_Create_Call {
	return &MockStoreRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockStoreRepository_Create_Call) Run(run func(ctx context.Context, s *model.Store)) *MockStoreRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Store
		if args[1] != nil {
			arg1 = args[1].(*model.Store)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreRepository_Create_Call) Return(err error) *MockStoreRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s *model.Store) error) *MockStoreRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockStoreRepository
func (_mock *MockStoreRepository) FindAll(ctx context.Context) ([]entity.Store, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entity.Store, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entity.Store); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockStoreRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStoreRepository_Expecter) FindAll(ctx interface{}) *MockStoreRepository_FindAll_Call {
	return &MockStoreRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockStoreRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockStoreRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreRepository_FindAll_Call) Return(stores []entity.Store, err error) *MockStoreRepository_FindAll_Call {
	_c.Call.Return(stores, err)
	return _c
}

func (_c *MockStoreRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]entity.Store, error)) *MockStoreRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockStoreRepository
func (_mock *MockStoreRepository) FindByID(ctx context.Context, id string) (*entity.Store, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Store, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Store); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStoreRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStoreRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockStoreRepository_FindByID_Call {
	return &MockStoreRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockStoreRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockStoreRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreRepository_FindByID_Call) Return(store *entity.Store, err error) *MockStoreRepository_FindByID_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *MockStoreRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Store, error)) *MockStoreRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockStoreRepository
func (_mock *MockStoreRepository) UpdateStatus(ctx context.Context, id string, status model.StoreStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.StoreStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStoreRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status model.StoreStatus
func (_e *MockStoreRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockStoreRepository_UpdateStatus_Call {
	return &MockStoreRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockStoreRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status model.StoreStatus)) *MockStoreRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.StoreStatus
		if args[2] != nil {
			arg2 = args[2].(model.StoreStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStoreRepository_UpdateStatus_Call) Return(err error) *MockStoreRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status model.StoreStatus) error) *MockStoreRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
